export const BREEDS = {
  dog: [
    'Labrador Retriever',
    'Golden Retriever',
    'German Shepherd',
    'French Bulldog',
    'Bulldog',
    'Poodle (Standard)',
    'Poodle (Miniature)',
    'Poodle (Toy)',
    'Beagle',
    'Rottweiler',
    'Dachshund',
    'Yorkshire Terrier',
    'Boxer',
    'Cavalier King Charles Spaniel',
    'Miniature Schnauzer',
    'Doberman Pinscher',
    'Pembroke Welsh Corgi',
    'Australian Shepherd',
    'Cocker Spaniel',
    'Shih Tzu',
    'Boston Terrier',
    'Havanese',
    'Pomeranian',
    'Chihuahua',
    'Maltese',
    'Great Dane',
    'Bernese Mountain Dog',
    'Pug',
    'Weimaraner',
    'Border Collie',
    'Basset Hound',
    'Chow Chow',
    'Shetland Sheepdog',
    'Brittany',
    'English Springer Spaniel',
    'Airedale Terrier',
    'West Highland White Terrier',
    'Whippet',
    'Saint Bernard',
    'Mastiff',
    'Samoyed',
    'Pekingese',
    'Afghan Hound',
    'Lhasa Apso',
    'Siberian Husky',
    'Alaskan Malamute',
    'Rhodesian Ridgeback',
    'Jack Russell Terrier',
    'Staffordshire Bull Terrier',
    'Mixed / Mestizo',
    'Otro',
  ],
  cat: [
    'Persian',
    'Maine Coon',
    'Ragdoll',
    'British Shorthair',
    'Bengal',
    'Siamese',
    'Abyssinian',
    'Birman',
    'Scottish Fold',
    'Sphynx',
    'Russian Blue',
    'American Shorthair',
    'Exotic Shorthair',
    'Burmese',
    'Tonkinese',
    'Oriental Shorthair',
    'Somali',
    'Havana Brown',
    'Chartreux',
    'Cornish Rex',
    'Devon Rex',
    'Selkirk Rex',
    'Norwegian Forest Cat',
    'Turkish Angora',
    'Bombay',
    'Manx',
    'Munchkin',
    'Singapura',
    'LaPerm',
    'Mixed / Mestizo',
    'Otro',
  ],
};
