import { Disease, DiseaseCategory, Species } from '../types';

const DISEASE_CATEGORIES: Record<DiseaseCategory, { label: string; icon: string; color: string }> = {
  infectious: { label: 'Infecciosas', icon: 'virus', color: '#E53935' },
  parasitic: { label: 'Parasitarias', icon: 'bug-outline', color: '#8E24AA' },
  degenerative: { label: 'Degenerativas', icon: 'trending-down', color: '#F57C00' },
  oncological: { label: 'Oncológicas', icon: 'alert-circle', color: '#C62828' },
  nutritional: { label: 'Nutricionales', icon: 'nutrition', color: '#43A047' },
  autoimmune: { label: 'Autoinmunes', icon: 'shield', color: '#1565C0' },
  traumatic: { label: 'Traumáticas', icon: 'bandage', color: '#6D4C41' },
  congenital: { label: 'Congénitas', icon: 'dna', color: '#00838F' },
  respiratory: { label: 'Respiratorias', icon: 'lungs', color: '#26A69A' },
  gastrointestinal: { label: 'Gastrointestinales', icon: 'stomach', color: '#7CB342' },
  dermatological: { label: 'Dermatológicas', icon: 'hand-heart', color: '#EC407A' },
  ocular: { label: 'Oculares', icon: 'eye', color: '#5C6BC0' },
  dental: { label: 'Dentales', icon: 'tooth', color: '#78909C' },
  endocrine: { label: 'Endocrinas', icon: 'flask', color: '#AB47BC' },
  cardiovascular: { label: 'Cardiovasculares', icon: 'heart-pulse', color: '#E53935' },
  neurological: { label: 'Neurológicas', icon: 'brain', color: '#7E57C2' },
  musculoskeletal: { label: 'Musculoesqueléticas', icon: 'bone', color: '#8D6E63' },
  renal: { label: 'Renales', icon: 'kidney', color: '#0097A7' },
  reproductive: { label: 'Reproductivas', icon: 'baby-carriage', color: '#EC407A' },
};

const DOG_DISEASES: Disease[] = [
  {
    id: 'dog-parvo',
    name: 'Parvovirus Canino',
    scientificName: 'Canine Parvovirus (CPV-2)',
    species: 'dog',
    category: 'infectious',
    severity: 'severe',
    description: 'Enfermedad viral altamente contagiosa causada por el parvovirus canino tipo 2. Afecta principalmente el tracto gastrointestinal y el sistema inmune. Es una de las enfermedades más comunes y mortales en cachorros no vacunados.',
    keySigns: [
      'Vómitos severos (a menudo con sangre)',
      'Diarrea hemorrágica (acuosa, fétida)',
      'Pérdida severa de apetito (anorexia)',
      'Letargia y debilidad extrema',
      'Fiebre alta (39.5-41°C)',
      'Deshidratación rápida',
      'Pérdida de peso abrupta',
      'Abdomen doloroso a la palpación',
    ],
    diagnosis: {
      clinicalExam: 'Evaluación de signos clínicos, deshidratación, estado corporal. Historial de vacunación incompleta.',
      labTests: [
        'Test rápido de antígeno fecal (ELISA) - alta sensibilidad',
        'Hemograma completo: leucopenia (linfopenía y neutropenia)',
        'Química sanguínea: hipoglucemia, hipoproteinemia, elevación de enzimas hepáticas',
        'Análisis de electrolitos: alteraciones por vómitos y diarrea',
      ],
      imaging: [
        'Radiografía abdominal: distensión de asas intestinales, patrón ileal anómalo',
      ],
      differentialDiagnosis: [
        'Parasitismo severo',
        'Gastroenteritis infecciosa por coronavirus',
        'Intoxicación alimentaria',
        'Enferadad inflamatoria intestinal',
      ],
    },
    treatment: {
      firstLine: [
        'Hospitalización y fluidoterapia IV agresiva (solución Ringer Lactato o Hartmann)',
        'Antieméticos: Maropitant (Cerenia) 1-2 mg/kg SC cada 24h',
        'Antibióticos de amplio espectro: Ampicilina 22 mg/kg IV q6h + Enrofloxacina 5 mg/kg IV q24h',
        'Protector gástrico: Omeprazol 1 mg/kg IV q24h',
        'Nutrición enteral suave cuando se tolere',
        'Monitoreo de glucemia: suplementación con dextrosa si <60 mg/dL',
      ],
      secondLine: [
        'Favipiravir (bajo investigación en veterinaria)',
        'Inmunoglobulinas antiparvovirus',
        'Plasma fresco de donadores vacunados',
        'Estimulantes de apetito: Acepromazina bajas dosis',
      ],
      emergency: 'Shock séptico: resucitación con fluidos bolus (90 mL/kg/h), dobutamina si hipotensión persiste, monitorización continua.',
      duration: '5-7 días de hospitalización. Pronóstico reservado si se inicia tratamiento tardío.',
    },
    prevention: [
      'Vacunación completa según protocolo: 4 dosis a partir de 6-8 semanas, refuerzo anual',
      'Evitar contacto con heces contaminadas',
      'Desinfección ambiental con hipoclorito de sodio (1:30)',
      'No pasear cachorros hasta completar el esquema vacunal',
      'Cuarentena de animales enfermos',
    ],
    prognosis: 'guarded',
    isZoonotic: false,
    references: [
      'Greene CE, Sykes JE. Canine Parvovirus Infections. In: Greene CE, ed. Infectious Diseases of the Dog and Cat. 4th ed. Elsevier; 2012.',
      'AVMA - Canine Parvovirus Fact Sheet',
    ],
  },
  {
    id: 'dog-moquillo',
    name: 'Moquillo Canino',
    scientificName: 'Canine Distemper Virus (CDV)',
    species: 'dog',
    category: 'infectious',
    severity: 'severe',
    description: 'Enfermedad viral sistémica altamente contagiosa causada por el virus del moquillo canino (familia Paramyxoviridae). Afecta tracto respiratorio, gastrointestinal, sistema nervioso central y tejidos epiteliales.',
    keySigns: [
      'Fiebre bifásica (primera subida 3-6 días, segunda 1-2 semanas)',
      'Secreción nasal y ocular mucopurulenta',
      'Tos seca progresiva a productiva',
      'Anorexia y depresión',
      'Hiperqueratosis de almohadillas plantares y nasales',
      'Signos neurológicos: mioclonias, convulsiones, ataxia',
      'Encefalitis en etapas tardías',
      'Petequias en mucosa oral',
    ],
    diagnosis: {
      clinicalExam: 'Signos sistémicos multifásicos, hiperqueratosis de almohadillas (signo patognomónico).',
      labTests: [
        'PCR en hisopos conjuntival/nasal y sangre',
        'Inmunofluorescencia directa en células epiteliales',
        'Hemograma: leucopenia linfocitaria',
        'Serología: titulación de anticuerpos IgG/IgM pareada',
      ],
      imaging: [
        'Radiografía torácica: patrón intersticial alveolar',
        'Radiografía craneal si signos neurológicos',
      ],
      differentialDiagnosis: [
        'Infección por influenza canina',
        'Adenovirus canino tipo 2',
        'Enfermedad de Carré',
        'Toxoplasmosis (gatos)',
      ],
    },
    treatment: {
      firstLine: [
        'Soporte intensivo: fluidoterapia IV',
        'Antibióticos para infecciones bacterianas secundarias: Doxiciclina 10 mg/kg PO q12-24h',
        'Antipiréticos: Metamizol 50 mg/kg IM (NO usar AINEs)',
        'Nebulización y fisioterapia torácica',
        'Nutrición asistida si anorexia severa',
        'Cuidado oftalmológico: lubricantes oculares, atropina tópica',
      ],
      secondLine: [
        'Interferón omega recombinante',
        'Inmunoglobulinas antimoquillo',
        'Anticonvulsivantes si signos neurológicos: Phenobarbital, Levetiracetam',
      ],
      emergency: 'Status epilépticus: Diazepam IV 0.5-1 mg/kg o Propofol IV. Encefalitis: pronóstico grave.',
      duration: '2-4 semanas. Secuelas neurológicas permanentes en 30-80% de los casos neurológicos.',
    },
    prevention: [
      'Vacunación: protocolo DHPPi a partir de 6-8 semanas con refuerzos cada 3-4 semanas hasta 16 semanas',
      'Refuerzo anual de por vida',
      'Evitar contacto con animales infectados o wildlife (mapaches, mustélidos)',
      'No pasear cachorros hasta completar vacunación',
    ],
    prognosis: 'guarded',
    isZoonotic: false,
    references: [
      'Greene CE, Appel MJG. Canine Distemper. In: Greene CE, ed. Infectious Diseases of the Dog and Cat. 4th ed. Elsevier; 2012.',
      'WTO - Canine Distemper Technical Disease Sheet',
    ],
  },
  {
    id: 'dog-lepto',
    name: 'Leptospirosis Canina',
    scientificName: 'Leptospira spp.',
    species: 'dog',
    category: 'infectious',
    severity: 'severe',
    description: 'Enfermedad zoonótica causada por espiroquetas del género Leptospira. Afecta hígado y riñones. Transmisión por contacto con orina de animales infectados, agua contaminada o suelo húmedo.',
    keySigns: [
      'Fiebre alta y repentina',
      'Mialgias severas (dolor muscular)',
      'Vómitos y diarrea',
      'Ictericia (coloración amarillente)',
      'Oliguria o anuria (insuficiencia renal agua)',
      'Polidipsia y poliuria',
      'Hemorragias petequiales',
      'Depresión severa',
      'Sangrado de encías',
    ],
    diagnosis: {
      clinicalExam: 'Ictericia, dolor renal a la palpación, fiebre, deshidratación. Historial de exposición a aguas estancadas.',
      labTests: [
        'MAT (Microscopic Agglutination Test) - Gold standard serológico',
        'PCR en sangre y orina',
        'Hemograma: trombocitopenia, leucocitosis con neutrilia',
        'Química: elevación marcada de ALT, AST, bilirrubina, creatinina, BUN',
        'Coagulograma: prolongación de TP y TPT',
      ],
      imaging: [
        'Radiografía abdominal: riñones agrandados o diminutos',
        'Ecografía renal: cambios parenquimatosos',
      ],
      differentialDiagnosis: [
        'Hepatitis infecciosa canina',
        'Piometra',
        'Intoxicación por zinc',
        'Babesiosis',
      ],
    },
    treatment: {
      firstLine: [
        'Fluidoterapia IV agresiva según función renal',
        'Doxiciclina 10 mg/kg PO q12h por 2-4 semanas (elimina portadores',
        'Ampicilina 22 mg/kg IV q6h',
        'Protectores renales: N-acetilcisteína',
        'Antieméticos: Maropitant 1-2 mg/kg SC q24h',
        'Transfusión de plaquetas si trombocitopenia severa',
      ],
      secondLine: [
        'Penicilina G cristalina 22,000-44,000 UI/kg IV q6h',
        'Hemodiálisis si falla renal aguda',
        'Plasma fresco para coagulopatía',
      ],
      emergency: 'Insuficiencia renal aguda con anuria: hemodiálisis o diálisis peritoneal. Manejo de hiperpotasemia.',
      duration: '2-4 semanas de antibióticos. Seguimiento renal por 3-6 meses.',
    },
    prevention: [
      'Vacunación anual (vacuna bivalente: L. canicola + L. icterohaemorrhagiae)',
      'Evitar contacto con aguas estancadas, charcos, ríos contaminados',
      'Control de roedores en el entorno',
      'Vigilancia en zonas endémicas (periodo de lluvias)',
    ],
    prognosis: 'guarded',
    isZoonotic: true,
    references: [
      'Sykes JE, et al. Leptospirosis. In: Greene CE, ed. Infectious Diseases of the Dog and Cat. 4th ed. Elsevier; 2012.',
      'CDC - Leptospirosis in Dogs',
    ],
  },
  {
    id: 'dog-rabies',
    name: 'Rabia',
    scientificName: 'Rabies lyssavirus',
    species: 'dog',
    category: 'infectious',
    severity: 'critical',
    description: 'Enfermedad viral zoonótica mortal causada por un Rhabdovirus. Afecta el sistema nervioso central. Transmisión por mordedura de animal infectado. Sin tratamiento curativo. Prevenida por vacunación.',
    keySigns: [
      'Fase prodrómica: cambios de comportamiento, fiebre, inapetencia',
      'Fase furiosa: agitación, agresividad, hiperexcitabilidad',
      'Fase paralítica: parálisis ascendente de extremidades posteriores',
      'Hidrofobia y aerofobia',
      'Excesiva salivación (hipersecreción)',
      'Deglución dificultosa',
      'Parálisis de mandíbula (mandíbula caída)',
      'Convulsiones',
    ],
    diagnosis: {
      clinicalExam: 'Signos neurológicos progresivos, historia de mordedura. Diagnóstico definitivo post-mortem.',
      labTests: [
        'IFA (Inmunofluorescencia directa) en tejido encefálico post-mortem',
        'Test de anticuerpos negativos en saliva',
        'PCR en tejido nervioso',
      ],
      imaging: [
        'No aplicable para diagnóstico ante-mortem',
      ],
      differentialDiagnosis: [
        'Encefalitis por toxoplasma',
        'Moquillo canino (fase neurológica)',
        ' intoxicación',
        'Encefalitis infecciosa',
      ],
    },
    treatment: {
      firstLine: [
        'NO EXISTE TRATAMIENTO CURATIVO',
        'Aislamiento inmediato obligatorio',
        'Eutanasia humanitaria recomendada',
        'Reporte obligatorio a autoridades sanitarias',
      ],
      secondLine: [],
      emergency: 'Protocolo de exposición: vacunación post-exposición para humanos expuestos. Reporte inmediato.',
      duration: 'Fatal en 100% de los casos una vez manifestados los signos.',
    },
    prevention: [
      'Vacunación ANUAL obligatoria (ley en la mayoría de países)',
      'Vacunación a partir de 3 meses de edad',
      'Control de animales callejeros',
      'Evitar contacto con fauna silvestre',
      'Reporte de mordeduras a autoridades sanitarias',
    ],
    prognosis: 'grave',
    isZoonotic: true,
    references: [
      'WHO - Rabies Fact Sheet',
      'OIE - Rabies Technical Disease Sheet',
      'CDC - Rabies in Dogs',
    ],
  },
  {
    id: 'dog-dysplasia-hip',
    name: 'Displasia Coxofemoral',
    scientificName: 'Canine Hip Dysplasia (CHD)',
    species: 'dog',
    category: 'musculoskeletal',
    severity: 'moderate',
    description: 'Enfermedad degenerativa multifactorial de desarrollo de la articulación coxofemoral. El acetábulo y la cabeza femoral no encajan correctamente, provocando laxitud articular, osteoarthritis y dolor crónico. Más común en razas grandes y gigantes.',
    keySigns: [
      'Cojera de extremidades posteriores (bilateral)',
      'Dificultad para levantarse',
      'Caminata "de conejo" (movimiento simultáneo de ambas patas traseras)',
      'Resistencia al ejercicio',
      'Dolor a la manipulación de caderas',
      'Atrofia muscular de muslos',
      'Amplio bascimiento posterior',
      'Síntomas empeoran con frío o ejercicio intenso',
    ],
    diagnosis: {
      clinicalExam: 'Prueba de Ortolani positiva (laxitud), dolor a la extensión/flexión de cadera, atrofia de músculos glúteos.',
      labTests: [
        'No hay pruebas de laboratorio específicas',
      ],
      imaging: [
        'Radiografía bajo sedación: posición ventrodorsal extendida',
        'Clasificación OFA: Excellent/Good/Fair/Dysplastic',
        'Clasificación FCI: Grados I-IV',
        'SCORE (evaluation method)',
        'CT o MRI para planificación quirúrgica',
      ],
      differentialDiagnosis: [
        'Osteocondritis disecante',
        'Enferadad de Legg-Calvé-Perthes',
        'Ruptura de ligamento cruzado craneal',
        'Osteomielitis',
      ],
    },
    treatment: {
      firstLine: [
        'Control de peso: mantener IMC ideal',
        'Ejercicio controlado: natación, paseos cortos',
        'AINEs: Carprofen 4.4 mg/kg PO q12-24h o Meloxicam 0.1 mg/kg PO q24h',
        'Suplementos: Glucosamina/condroitina, ácido hialurónico, omega-3',
        'Fisioterapia y rehabilitación',
        'Acupuntura',
      ],
      secondLine: [
        'Infiltración intraarticular con ácido hialurónico o PRP',
        'Osteotomía pélvica (triple osteotomía)',
        'Escisión de cabeza y cuello femoral',
        'Prótesis total de cadera',
      ],
      emergency: 'Crisis de dolor agudo: AINEs parenterales + analgesia multimodal.',
      duration: 'Manejo de por vida. Cirugía: recuperación 8-12 semanas.',
    },
    prevention: [
      'Selección genética: evaluación de padres antes de cría (OFA/FCI)',
      'Control nutricional en cachorros de razas grandes: no sobrealimentar',
      'Evitar ejercicio excesivo en crecimiento',
      'Suplementación con glucosamina en razas predisuestas',
      'Mantenimiento de peso ideal durante toda la vida',
    ],
    prognosis: 'good',
    isZoonotic: false,
    references: [
      'Smith GK, et al. Hip Dysplasia. In: Fossum TW, ed. Small Animal Surgery. 5th ed. Elsevier; 2018.',
      'OFA - Canine Hip Dysplasia Information',
    ],
  },
  {
    id: 'dog-heartworm',
    name: 'Dirofilariasis (Gusano del Corazón)',
    scientificName: 'Dirofilaria immitis',
    species: 'dog',
    category: 'parasitic',
    severity: 'severe',
    description: 'Enfermedad parasitaria transmitida por mosquitos causada por el nematodo Dirofilaria immitis. Los gusanos adultos se alojan en las arterias pulmonares y corazón derecho, causando enfermedad cardiopulmonar.',
    keySigns: [
      'Tos crónica progresiva',
      'Intolerancia al ejercicio',
      'Disnea (dificultad respiratoria)',
      'Cianosis',
      'Ascitis (acumulación de líquido abdominal)',
      'Insuficiencia cardíaca derecha',
      'Pérdida de peso',
      'Hemoptisis (sangre en esputo)',
      'Síncopal (desmayos)',
    ],
    diagnosis: {
      clinicalExam: 'Soplo cardíaco (regurgitación tricuspídea), ingurgitación yugular, ascitis, hepatomegalia.',
      labTests: [
        'Test antígeno cardíaco (SNAP 4Dx) - detecta hembras adultas',
        'Microhematocrito: evidencia de gusanos ("Wuhan strips")',
        'Hemograma: eosinofilia, trombocitopenia',
        'Ecocardiografía: gusanos en arteria pulmonar/VD',
      ],
      imaging: [
        'Radiografía toracicA: enlargement de arterias pulmonares, infiltrados',
        'Ecocardiografía: visualización directa de gusanos',
      ],
      differentialDiagnosis: [
        'Enferadad cardíaca valvular degenerativa',
        'Neumonía',
        'Enfermedad pulmonar tromboembólica',
        'Fibrosis pulmonar',
      ],
    },
    treatment: {
      firstLine: [
        'Restricción estricta de ejercicio por 4-6 semanas',
        'Melarsamina dihidrocloruro: 2.5 mg/kg IM 2 veces a 24h, luego 2.5 mg/kg IM a los 60 días',
        'Doxiciclina 10 mg/kg PO q12h por 4 semanas (Wolbachia)',
        'Prednisona 1 mg/kg PO tapering por 2 semanas',
        'Estabilización cardíaca previa si enfermedad avanzada',
      ],
      secondLine: [
        'Cirugía extractiva de gusanos (rara vez indicada)',
        'Tratamiento del gusano de Dirofilaria repens (si infestación mixta)',
      ],
      emergency: 'Tromboembolismo pulmonar masivo: oxigenoterapia, anticoagulantes (heparina), corticoides, soporte cardiovascular.',
      duration: 'Tratamiento completo: 4 meses. Evitar ejercicio durante 6-8 semanas post-tratamiento.',
    },
    prevention: [
      'Profilaxis mensual: Moxidectina, Ivermectina o Milbemicina oxima',
      'Iniciar profilaxis a los 8 semanas de edad',
      'Test anual antes de iniciar/prevenir profilaxis',
      'Control de mosquitos: repellentes, mosquiteros',
      'No administrar preventivos a perros con gusanos adultos sin tratamiento previo',
    ],
    prognosis: 'good',
    isZoonotic: false,
    references: [
      'GVAC - Guidelines for the Diagnosis, Prevention, and Management of Dirofilaria immitis Infection in Dogs',
      'American Heartworm Society - Current Canine Guidelines',
    ],
  },
  {
    id: 'dog-diabetes',
    name: 'Diabetes Mellitus',
    scientificName: 'Diabetes Mellitus Canine',
    species: 'dog',
    category: 'endocrine',
    severity: 'moderate',
    description: 'Trastorno endocrino caracterizado por hiperglucemia persistente debido a deficiencia absoluta o relativa de insulina. Más común en hembras no castradas, razas como Caniche, Maltés, Schnauzer miniatura.',
    keySigns: [
      'Polidipsia (bebe mucha agua)',
      'Poliuria (orina en exceso)',
      'Polidifagia (come mucho) con pérdida de peso',
      'Cataratas bilaterales (frecuente)',
      'Letargia',
      'Aumento de volumen del hígado (hepatomegalia)',
      'Orina de olor dulce',
      'Infecciones urinarias recurrentes',
    ],
    diagnosis: {
      clinicalExam: 'Pérdida de peso a pesar de apetito conservado, cataratas, hepatomegalia.',
      labTests: [
        'Glucemia en ayuno: >250 mg/dL (normal: 70-120)',
        'Glucosuria (orina con glucosa)',
        'Hemograma: puede ser normal',
        'Química: elevación de fosfatasa alcalina, triglicéridos',
        'Fructosamina: >400 µmol/L (evalúa control glucémico promedio)',
        'Análisis de orina: infecciones concurrentes',
      ],
      imaging: [
        'Ecografía abdominal: evaluación de páncreas y hígado',
      ],
      differentialDiagnosis: [
        'Hiperadrenocorticismo (Cushing)',
        'Pancreatitis',
        'Enfermedad renal',
        'Hipertiroidismo (gatos)',
      ],
    },
    treatment: {
      firstLine: [
        'Insulina: Insulina NPH (Humulin N) o Caninsulin/Vetsulin',
        'Dosis inicial: 0.25-0.5 UI/kg SC q12h',
        'Alimentación consistente: dieta alta en fibra (Hills w/d, Royal Canin W/S)',
        'Horarios fijos de comidas sincronizados con insulina',
        'Monitoreo de glucemia: curvas de glucemia cada 1-2 semanas',
        'Ejercicio regular y consistente',
      ],
      secondLine: [
        'Insulina glargina (Lantus) para mejor control',
        'Metformina 10-25 mg/kg PO q12h (adjuvante)',
        'Peglispro (investigación)',
      ],
      emergency: 'Cetoacidosis diabética: fluidoterapia IV, insulina regular IV, monitoreo de electrolitos y pH.',
      duration: 'Tratamiento de por vida. Monitoreo continuo.',
    },
    prevention: [
      'Esterilización temprana en hembras (reduce riesgo significativamente)',
      'Control de peso',
      'Alimentación balanceada de alta calidad',
      'Ejercicio regular',
      'Screening en razas predisuestas',
    ],
    prognosis: 'good',
    isZoonotic: false,
    references: [
      'Nelson RW, Reusch CE. Animal Models of Disease: Classification and Etiology of Diabetes in Dogs and Cats. Endocrinology. 2014.',
      'AAHA - Canine Diabetes Management Guidelines',
    ],
  },
  {
    id: 'dog-pancreatitis',
    name: 'Pancreatitis',
    scientificName: 'Pancreatitis Canina',
    species: 'dog',
    category: 'gastrointestinal',
    severity: 'moderate',
    description: 'Inflamación del páncreas que puede ser aguda o crónica. Es una causa frecuente de enfermedad gastrointestinal en perros. Predisposición en razas como Schnauzer miniatura, Cocker Spaniel, Yorkshire Terrier.',
    keySigns: [
      'Vómitos recurrentes',
      'Dolor abdominal (posición "oración": miembros anteriores extendidos, posterior elevados)',
      'Anorexia',
      'Diarrea (a veces esteatorrea)',
      'Letargia',
      'Fiebre',
      'Deshidratación',
      'Distensión abdominal',
    ],
    diagnosis: {
      clinicalExam: 'Dolor abdominal a la palpación, posición characterize, deshidratación.',
      labTests: [
        'Spec cPL (Pancreatic Lipase Immunoreactivity) - test específico',
        'PLI sérica: elevada (>200 µg/L sugiere pancreatitis)',
        'Amilasa/lipasa: elevadas (poco específicas)',
        'Hemograma: puede haber leucocitosis',
        'Química: elevación de ALT, AST, bilirrubina',
        'Análisis de orina',
      ],
      imaging: [
        'Ecografía abdominal: páncreas agrandado, hiperecogénico, líquido peripancreático',
        'Radiografía abdominal: puede ser normal o mostrar masa en cuadrante anterior',
      ],
      differentialDiagnosis: [
        'Hepatitis',
        'Enferadad inflamatoria intestinal',
        'Obstrucción intestinal',
        'Insuficiencia renal aguda',
      ],
    },
    treatment: {
      firstLine: [
        'NPO 24-48 horas, luego dieta blanda gradual',
        'Fluidoterapia IV: Ringer Lactato para rehidratación',
        'Maropitant (Cerenia) 1-2 mg/kg SC/IV q24h',
        'Omeprazol 1 mg/kg IV q24h o Pantoprazol',
        'Buprenorfina 0.02-0.03 mg/kg IV/SC q6-8h para dolor',
        'Nutrición enteral temprana (sonda nasogástrica si no come)',
      ],
      secondLine: [
        'Gabapentina 5-10 mg/kg PO q8h (dolor crónico)',
        'Pentoxifilina 10 mg/kg PO q8-12h',
        'Antibióticos solo si pancreatitis supurada/necrótica',
      ],
      emergency: 'Pancreatitis hemorrágica/necrótica: UCI, fluidoterapia agresiva, analgesia continua, transfusión si sangrado.',
      duration: 'Aguda: 3-5 días hospitalización. Crónica: manejo dietético de por vida.',
    },
    prevention: [
      'Dieta baja en grasa',
      'Control de peso estricto',
      'Evitar sobras de comida y golosinas grasas',
      'Raciones fraccionadas (comidas pequeñas frecuentes)',
      'Castración en razas predisuestas',
    ],
    prognosis: 'good',
    isZoonotic: false,
    references: [
      'Newman S, et al. Pancreatitis in Dogs. In: Ettinger SJ, ed. Textbook of Veterinary Internal Medicine. 8th ed. Elsevier; 2017.',
      'ACVIM - Consensus Statement on Pancreatitis in Dogs and Cats',
    ],
  },
  {
    id: 'dog-bloat',
    name: 'Torsión Gástrica (Bloat)',
    scientificName: 'Gastric Dilatation-Volvulus (GDV)',
    species: 'dog',
    category: 'gastrointestinal',
    severity: 'critical',
    description: 'Emergencia quirúrgica donde el estómago se dilata con gas y torsiona sobre su eje, obstruyendo entrada y salida. Compromete retorno venoso y puede causar shock, necrosis gástrica y muerte. Mayor incidencia en razas grandes de pecho profundo.',
    keySigns: [
      'Distensión abdominal aguda (timpanismo)',
      'Esfuerzo infructuoso por vomitar (gagging)',
      'Salivación excesiva',
      'Inquietud, deambulación',
      'Taquicardia y debilidad progresiva',
      'Encías pálidas o azuladas',
      'Colapso y shock',
      'Abdomen doloroso a la percusión (timpanismo)',
    ],
    diagnosis: {
      clinicalExam: 'Timpanismo abdominal, retching sin producción, mucosas pálidas/cianóticas, taquicardia.',
      labTests: [
        'Hemograma: hemoconcentración, trombocitopenia',
        'Química: acidosis metabólica, hiperpotasemia, elevación de lactato',
        'Gasometría arterial: acidosis mixta',
        'Coagulograma: DIC en casos avanzados',
        'Troponina I: elevada (miocardio dañado)',
      ],
      imaging: [
        'Radiografía abdominal: estómago dilatado con gas, signo "double bubble" (volvulus)',
      ],
      differentialDiagnosis: [
        'Dilatación gástrica simple (sin volvulus)',
        'Obstrucción intestinal',
        'Esplenomegalia',
        'Tumor abdominal',
      ],
    },
    treatment: {
      firstLine: [
        'DECOMPRECIÓN URGENTE: sonda nasogástrica o gastocentesis',
        'Resucitación con fluidos IV agresiva (shock: 90 mL/kg/h)',
        'Corrección de acidosis: bicarbonato de sodio',
        'Corrección de hiperpotasemia: insulina + dextrosa',
        'Espirómetro incentivo y descomprimación continua',
        'CIRUGÍA URGENTE: gastropexia + desvolvimiento',
        'Monitorización cardíaca continua',
      ],
      secondLine: [
        'Gastropexia profiláctica preventiva',
        'Maropitant para náuseas post-operatorias',
        'Antibióticos profilácticos: Cefazolina 22 mg/kg IV',
      ],
      emergency: 'SHOCK: fluidoterapia masiva, dobutamina si FR <60, transmisión de plasma, corrección de coagulopatía.',
      duration: 'Hospitalización 3-5 días. Cirugía: recuperación 2-3 semanas.',
    },
    prevention: [
      'Alimentación fraccionada (2-3 comidas/día)',
      'Evitar ejercicio intensa 1 hora antes/después de comer',
      'Bol de alimentación lento o puzzle feeder',
      'Gastropexia profiláctica en razas predisuestas (Great Dane, Doberman, etc.)',
      'No usar tolvaneras elevadas',
      'Evitar estrés durante comidas',
    ],
    prognosis: 'guarded',
    isZoonotic: false,
    references: [
      'Glickman LT, et al. Canine Gastric Dilatation-Volvulus. JAVMA. 2000.',
      'ACVS - GDV in Dogs Surgical Principles',
    ],
  },
  {
    id: 'dog-dental',
    name: 'Enfermedad Periodontal',
    scientificName: 'Periodontal Disease Canine',
    species: 'dog',
    category: 'dental',
    severity: 'moderate',
    description: 'Inflamación e infección de las estructuras de soporte del diente (encía, ligamento periodontal, cemento, hueso alveolar). Es la enfermedad más común en perros adultos, afectando al 80% a los 3 años de edad.',
    keySigns: [
      'Mal aliento (halitosis)',
      'Acumulación de sarro (cálculo dental)',
      'Encías rojas e inflamadas (gingivitis)',
      'Sangrado de encías al masticar o cepillar',
      'Pérdida de dientes',
      'Dolor oral (rechazo de alimento, babeo)',
      'Abscesos periapicales',
      'Fístulas oronasales',
    ],
    diagnosis: {
      clinicalExam: 'Evaluación visual de sarro, gingivitis, movilidad dental. Odontograma completo.',
      labTests: [
        'Hemograma si infección sistémica',
        'Cultivo y antibiograma si absceso',
      ],
      imaging: [
        'Radiografías dentales intraorales: evaluación de hueso alveolar, raíces, abscesos',
        'Necesarias para clasificar estadio de enfermedad periodontal',
      ],
      differentialDiagnosis: [
        'Fractura dental',
        'Tumor oral',
        'Estomatitis',
        'Enferadad renal (halitosis urémica)',
      ],
    },
    treatment: {
      firstLine: [
        'Limpieza dental profunda bajo anestesia general',
        'Raspado supragingival e infragingival',
        'Pulido dental',
        'Extracción de dientes comprometidos',
        'Antibióticos: Clindamicina 10 mg/kg PO q12h por 7-10 días',
        'Enjuagues con clorhexidina 0.12%',
        'Analgesia post-operatoria: Carprofen + Tramadol',
      ],
      secondLine: [
        'Cirugía periodontal (colgajos)',
        'Injertos óseos para defects óseos',
        'Gel de doxiciclina subgingival (PerioStat)',
      ],
      emergency: 'Absceso dental con cellulitis facial: drenaje + antibióticos IV.',
      duration: 'Mantenimiento dental diario. Revisión dental anual.',
    },
    prevention: [
      'Cepillado diario con pasta dental veterinaria',
      'Dietas dentales (Hills t/d, Royal Canin Dental)',
      'Chews dentales aprobados por VOHC',
      'Sprays/enjuagues con clorhexidina',
      'Limpieza dental profesional anual',
    ],
    prognosis: 'good',
    isZoonotic: false,
    references: [
      'AVDC - Veterinary Dental Nomenclature',
      'AAHA - Dental Care Guidelines for Dogs and Cats',
    ],
  },
  {
    id: 'dog-allergies',
    name: 'Dermatitis Atópica',
    scientificName: 'Canine Atopic Dermatitis (CAD)',
    species: 'dog',
    category: 'dermatological',
    severity: 'moderate',
    description: 'Enfermedad inflamatoria de la piel genéticamente predispuesta, mediada por IgE, caracterizada por prurito. Afecta al 10-15% de los perros. Suele manifestarse entre 1-3 años de edad.',
    keySigns: [
      'Prurito intenso y crónico (principal signo)',
      'Rascado, lamido, mordisqueo de zonas afectadas',
      'Eritema (enrojecimiento) en axilas, ingles, abdomen',
      'Otitis externa recurrente',
      'Dermatitis podal (lamido de patas)',
      'Infecciones cutáneas secundarias (piodermas)',
      'Engrosamiento de piel (liquenificación)',
      'Alopecia autotraumática',
    ],
    diagnosis: {
      clinicalExam: 'Distribución characterize: axilas, ingles, podal, facial. Prurito sin parasitismo demostrable.',
      labTests: [
        'Raspado de piel: descartar sarna (Sarcoptes, Demodex)',
        'Citología cutánea: infección secundaria (Staph, Malassezia)',
        'Alergenos específicos IgE sérica o intradérmica',
        'Hemograma: eosinofilia (no siempre presente)',
      ],
      imaging: [],
      differentialDiagnosis: [
        'Dermatitis alérgica por pulgas (DAPP)',
        'Dermatofitosis',
        'Sarna sarcóptica',
        'Alergia alimentaria',
        'Dermatitis seborreica',
      ],
    },
    treatment: {
      firstLine: [
        'Control de alérgenos: filtros HEPA, baño semanal con champú suave',
        'Oclacitinib (Apoquel) 0.4-0.6 mg/kg PO q12h por 14 días, luego q24h',
        'Corticoides: Prednisona 0.5-1 mg/kg PO tapering (uso a corto plazo)',
        'Antihistamínicos: Cetirizina 5-10 mg PO q12-24h (efecto variable)',
        'Tratamiento de infecciones secundarias',
      ],
      secondLine: [
        'Ciclosporina 5 mg/kg PO q24h (2-4 meses para efecto)',
        'Inmunoterapia alérgeno-específica (SCIT o SLIT)',
        'Spray tópico: Lokivetmab (Cytopoint) 0.4-1.0 mg/kg SC q4-8w',
        'Ácidos grasos omega-3 y omega-6',
        'Shampoo medicado: clorhexidina, avena colloidal',
      ],
      emergency: 'Dermatitis aguda severa con auto-traumatismo: collar isabelino + corticoides parenterales.',
      duration: 'Manejo de por vida. Combinación terapéutica según respuesta.',
    },
    prevention: [
      'Dieta hipoalergénica o de eliminación',
      'Control estricto de pulgas',
      'Baños regulares con champú suave',
      'Suplementación con omega-3',
      'Ambiente libre de alérgenos (lavado de camas frecuente)',
    ],
    prognosis: 'guarded',
    isZoonotic: false,
    references: [
      'Olivry T, et al. Treatment of Canine Atopic Dermatitis: 2015 Clinical Guidelines. Vet Dermatol. 2015.',
      'ISVD - Canine Atopic Dermatitis Guidelines',
    ],
  },
  {
    id: 'dog-cataracts',
    name: 'Cataratas',
    scientificName: 'Cataracts Canine',
    species: 'dog',
    category: 'ocular',
    severity: 'moderate',
    description: 'Opacificación del cristalino que impide el paso normal de la luz a la retina. Puede ser unilateral o bilateral, congénita o adquirida. Es una causa importante de ceguera en perros.',
    keySigns: [
      'Opacidad blanca/azulada en la pupila',
      'Reflejo pupilar alterado',
      'Ceguera parcial o total',
      'Nistagmo (movimientos oculares involuntarios)',
      'Iris adicionalmente adherido al cristalino (sinéquia)',
      'Ojo rojo (uveítis asociada)',
    ],
    diagnosis: {
      clinicalExam: 'Examen con oftalmoscopio directo e indirecto. Evaluación del reflejo rojo.',
      labTests: [
        'Ecografía ocular si no se visualiza fondo de ojo',
        'Tonometría: descartar glaucoma',
        'Electrorretinograma (ERG) prequirúrgico',
      ],
      imaging: [
        'Ecografía ocular B-scan',
        'Fotografía del segmento anterior',
      ],
      differentialDiagnosis: [
        'Esclerosis nuclear (normal envejecimiento)',
        'Glaucoma',
        'Uveítis anterior',
        'Displasia retiniana',
      ],
    },
    treatment: {
      firstLine: [
        'Facoemulsificación + implantación de lente intraocular (IOL)',
        'Pre-anestesia completa: hemograma, química, ecocardiograma',
        'Tratamiento pre-operatorio de uveítis: prednisolona tópica',
        'Gotas post-operatorias: Prednisolona acetato 1%, atropina, ofloxacino',
        'Collar isabelino por 2 semanas',
      ],
      secondLine: [
        'Extracción extracapsular si cristalino hiper maduro',
        'Manejo médico si no es candidato quirúrgico',
      ],
      emergency: 'Glaucoma secundario: manitol IV + timolol tópico + acetazolamida PO.',
      duration: 'Recuperación visual: 2-6 semanas. Gotas tópicas por 4-6 semanas.',
    },
    prevention: [
      'Cribado genético en razas predisuestas',
      'Control de diabetes (cataratas diabéticas)',
      'Exámenes oculares regulares',
      'Tratamiento temprano de uveítis',
    ],
    prognosis: 'good',
    isZoonotic: false,
    references: [
      'Gelatt KN, et al. Canine Cataracts. In: Gelatt KN, ed. Veterinary Ophthalmology. 5th ed. Elsevier; 2013.',
      'ACVO - Canine Cataract Guidelines',
    ],
  },
  {
    id: 'dog-kidney',
    name: 'Enfermedad Renal Crónica',
    scientificName: 'Chronic Kidney Disease (CKD)',
    species: 'dog',
    category: 'renal',
    severity: 'moderate',
    description: 'Pérdida progresiva e irreversible de la función renal. Más común en perros geriátricos. IRIS staging I-IV. La pérdida del 75% de nefronas precede a los signos clínicos.',
    keySigns: [
      'Polidipsia y poliuria',
      'Pérdida de peso progresiva',
      'Anorexia',
      'Vómitos',
      'Halitosis urémica (olor a amoníaco)',
      'Letargia',
      'Pelo seco y quebradizo',
      'Úlceras orales',
      'Anemia (mucosas pálidas)',
    ],
    diagnosis: {
      clinicalExam: 'Pérdida de peso, deshidratación, halitosis, renales de tamaño reducido.',
      labTests: [
        'Creatinina y BUN elevadas (consistencia en 2 muestras)',
        'SDMA >18 µg/dL (más sensible que creatinina)',
        'Análisis de orina: isostenuria, proteinuria',
        'Relación proteína/creatinina en orina (UPC)',
        'Fosfatasa alcalina elevada',
        'Electrolitos: hiperpotasemia, hipercalcemia',
        'Hemograma: anemia normocítica normocrómica',
      ],
      imaging: [
        'Ecografía renal: riñones pequeños, irregularidad cortical',
        'Radiografía abdominal: riñones de tamaño reducido',
      ],
      differentialDiagnosis: [
        'CKD vs. enfermedad renal aguda',
        'Nefropatía por amiloidosis',
        'Nefritis intersticial',
        'Pielonefritis',
      ],
    },
    treatment: {
      firstLine: [
        'Dieta renal (Hills k/d, Royal Canin Renal)',
        'Restrictiva en fósforo y proteína de alta calidad',
        'Fosfato de aluminio si hiperfosfatemia',
        'Fluidoterapia subcutánea en casa (100-150 mL/q24-48h)',
        'Eritropoyetina (EPO) si anemia severa',
        'Antiácidos: Famotidina 0.5 mg/kg PO q12-24h',
        'Proteínas de unión a fósforo',
      ],
      secondLine: [
        'Telmisartán (Semintra) para proteinuria',
        'Epodarb (ESAs)',
        'Calcitriol (vitamina D activa)',
      ],
      emergency: 'Crisis urémica: fluidoterapia IV, corrección de electrolitos, diálisis peritoneal.',
      duration: 'Manejo de por vida con supervisión regular de valores renales.',
    },
    prevention: [
      'Dieta de calidad durante toda la vida',
      'Hidratación adecuada (bebederos de agua corriente)',
      'Evitar AINEs y nefrotóxicos',
      'Exámenes de sangre anuales en senior (>7 años)',
      'Control de presión arterial',
    ],
    prognosis: 'guarded',
    isZoonotic: false,
    references: [
      'IRIS - Staging and Treatment of CKD in Dogs and Cats',
      'Polzin DJ. Chronic Kidney Disease in Dogs. In: Ettinger SJ, ed. 8th ed. Elsevier; 2017.',
    ],
  },
  {
    id: 'dog-lymphoma',
    name: 'Linfoma Canino',
    scientificName: 'Canine Lymphoma',
    species: 'dog',
    category: 'oncological',
    severity: 'severe',
    description: 'Neoplasia de células linfoides, una de las más comunes en perros. Afecta tejidos linfoides (nodos, bazo, médula ósea, tracto GI). Múltiples subtipos con diferentes pronósticos.',
    keySigns: [
      'Linfadenopatía periférica (nodos aumentados)',
      'Pérdida de peso progresiva',
      'Anorexia',
      'Letargia',
      'Fiebre',
      'Vómitos y diarrea (forma GI)',
      'Dificultad respiratoria (forma mediastínica)',
      'Piel: nódulos o úlceras (forma cutánea)',
    ],
    diagnosis: {
      clinicalExam: 'Palpación de nodos linfáticos periféricos agrandados, hepatomegalia, esplenomegalia.',
      labTests: [
        'Citología por aspiración con aguja fina (FNA) de nódulos',
        'Biopsia con inmunohistoquímica para subtipaje',
        'Hemograma: puede haber linfocitosis o linfopenia',
        'Química: hipercalcemia en algunos casos',
        'Frotis de sangre periférica',
      ],
      imaging: [
        'Radiografía torácica: nódulos mediastínicos, effusión pleural',
        'Ecografía abdominal: nódulos hepáticos/esplénicos',
      ],
      differentialDiagnosis: [
        'Hiperplasia reactiva de nódulos',
        'Infección por Ehrlichia',
        'Otras neoplasias',
      ],
    },
    treatment: {
      firstLine: [
        'Quimioterapia: protocolo CHOP (Ciclofosfamida, Doxorubicina, Vincristina, Prednisona)',
        'Protocolo Madison-Wisconsin para linfoma de alto grado',
        'Prednisona 1-2 mg/kg PO tapering',
        'Monitorización de toxicidad mielosupresora',
      ],
      secondLine: [
        'Lomustina (CCNU) para recaída',
        'Toceranib (Palladia)',
        'Masivetib (Kinavet)',
        'Tratamiento paliativo',
      ],
      emergency: 'Linfoma de células T: hipercalcemia → fluidoterapia + furosemida.',
      duration: 'Quimioterapia: 25-30 semanas. Remisión promedio: 6-12 meses.',
    },
    prevention: [
      'No hay prevención conocida',
      'Castración puede reducir riesgo (hembras)',
      'Detección temprana: examen físico regular',
      'Screening en razas predisuestas (Golden Retriever, Boxer, Bulldog)',
    ],
    prognosis: 'guarded',
    isZoonotic: false,
    references: [
      'Vail DM, et al. Lymphoma. In: Withrow SJ, Vail DM, eds. Small Animal Clinical Oncology. 5th ed. Elsevier; 2013.',
      'ECVIM - Canine Lymphoma Guidelines',
    ],
  },
  {
    id: 'dog-ear-infection',
    name: 'Otitis Externa',
    scientificName: 'Otitis Externa Canine',
    species: 'dog',
    category: 'dermatological',
    severity: 'mild',
    description: 'Inflamación e infección del canal auditivo externo. Es una de las razones más comunes de consulta veterinaria. Predisposición en razas con orejas péndulas (Cocker Spaniel, Labrador, Basset Hound).',
    keySigns: [
      'Sacudida frecuente de cabeza',
      'Rascado de orejas',
      'Cojera de cabeza hacia el lado afectado',
      'Secreción del canal auditivo (cerumen, pus, sangre)',
      'Mal olor en oídos',
      'Eritema e inflamación del pabellón auricular',
      'Estenosis del canal auditivo (crónico)',
      'Dolor a la palpación de orejas',
    ],
    diagnosis: {
      clinicalExam: 'Otoscopia: evaluación del canal y tímpano. Identificación de la causa.',
      labTests: [
        'Citología del cerumen: bacterias (Staph, Pseudomonas), levaduras (Malassezia)',
        'Cultivo y antibiograma si infección resistente',
        'Cálculos de cerumen',
      ],
      imaging: [
        'Radiografías del oído si sospecha de otitis media',
        'TAC si sospecha de otitis interna',
      ],
      differentialDiagnosis: [
        'Otitis media/interna',
        'Otodecosis (ácaros)',
        'Cuerpo extraño',
        'Neoplasia del canal auditivo',
        'Dermatitis alérgica como causa subyacente',
      ],
    },
    treatment: {
      firstLine: [
        'Limpieza suave del canal con solución otológica',
        'Gotas otológicas: Polimixina B + Neomicina + Prednisolona',
        'Antibióticos tópicos según citología',
        'Antifúngicos si Malassezia: Clotrimazol',
        'Tratamiento de la causa subyacente',
        'Collar isabelino si auto-traumatismo',
      ],
      secondLine: [
        'Antibióticos sistémicos si otitis severa',
        'Cirugía (ablación del canal) si otitis crónica con estenosis',
        'Desbridamiento quirúrgico',
      ],
      emergency: 'Otitis interna con signos neurológicos: internamiento y tratamiento intensivo.',
      duration: 'Aguda: 7-14 días. Crónica: semanas a meses según causa.',
    },
    prevention: [
      'Limpieza preventiva de orejas semanal con solución suave',
      'Secar orejas después de nadar/bañarse',
      'Tratar causas subyacentes (alergias)',
      'Trimming del pelo del canal auditivo en razas predisuestas',
    ],
    prognosis: 'excellent',
    isZoonotic: false,
    references: [
      'Cole LK, et al. Otitis Externa in Dogs and Cats. Vet Clin North Am Small Anim Pract. 2004.',
      'AVDA - Guidelines for Management of Otitis Externa',
    ],
  },
];

const CAT_DISEASES: Disease[] = [
  {
    id: 'cat-felv',
    name: 'Leucemia Felina',
    scientificName: 'Feline Leukemia Virus (FeLV)',
    species: 'cat',
    category: 'infectious',
    severity: 'severe',
    description: 'Infección retroviral que causa inmunosupresión, anemia y neoplasias en gatos. Principal causa de muerte en gatos jóvenes. Transmisión por contacto cercano (saliva, secreciones nasales, leche).',
    keySigns: [
      'Pérdida de peso progresiva',
      'Letargia persistente',
      'Anorexia',
      'Fiebre recurrente',
      'Anemia (mucosas pálidas)',
      'Linfadenopatía',
      'Infecciones secundarias frecuentes',
      'Tumores (linfoma, leucemia)',
      'Pelo en mal estado',
    ],
    diagnosis: {
      clinicalExam: 'Pérdida de peso, anemia, linfadenopatía, fiebre, infecciones recurrentes.',
      labTests: [
        'ELISA para antígeno p27 (screening) - en sangre',
        'IFA para确认 infección persistente',
        'PCR para ADN viral',
        'Hemograma: anemia regenerativa o no regenerativa, leucopenia/leucocitosis',
        'Química: puede haber hiperglobulinemia',
      ],
      imaging: [
        'Radiografía torácica: masas mediastínicas (linfoma)',
        'Ecografía abdominal: linfadenopatía',
      ],
      differentialDiagnosis: [
        'FIV (infección por virus de inmunodeficiencia felina)',
        'Toxoplasmosis',
        'Anemia infecciosa felina',
      ],
    },
    treatment: {
      firstLine: [
        'Aislamiento de otros gatos',
        'Soporte nutricional: dieta de alta calidad',
        'Antibióticos para infecciones secundarias',
        'Interferón recombinante felino (rFeIFN)',
        'Roncoleukina (inmunomodulador)',
        'Antivirales: AZT (Zidovudina)',
        'Transfusiones si anemia severa',
      ],
      secondLine: [
        'Quimioterapia si linfoma (protocolo COP o CHOP)',
        'Lomustina',
        'Estimulantes de médula ósea',
      ],
      emergency: 'Shock séptico por inmunosupresión: antibioticoterapia IV amplio espectro, fluidoterapia.',
      duration: 'Enfermedad de por vida. Supervivencia variable: meses a años.',
    },
    prevention: [
      'Vacunación: protocolo FeLV a partir de 8-9 semanas, refuerzo a las 12 semanas, anual',
      'Test FeLV antes de vacunar',
      'Aislamiento de gatos FeLV positivos',
      'No mezclar gatos seronegativos con seropositivos',
      'Mantener gatos en interiores',
    ],
    prognosis: 'poor',
    isZoonotic: false,
    references: [
      'Hartmann K, et al. Feline Leukemia Virus Infection. In: Greene CE, ed. 4th ed. Elsevier; 2012.',
      'AAFP - Feline Leukemia Virus Disease Complex Guidelines',
    ],
  },
  {
    id: 'cat-fiv',
    name: 'Virus de Inmunodeficiencia Felina',
    scientificName: 'Feline Immunodeficiency Virus (FIV)',
    species: 'cat',
    category: 'infectious',
    severity: 'moderate',
    description: 'Infección retroviral que causa inmunodeficiencia progresiva similar al VIH en humanos. Transmisión principal por mordedura. Más común en machos callejeros no castrados.',
    keySigns: [
      'Infecciones recurrentes (bacterianas, fúngicas)',
      'Estomatitis crónica (inflamación severa de boca)',
      'Pérdida de peso',
      'Letargia',
      'Fiebre intermitente',
      'Linfadenopatía',
      'Dermatitis crónica',
      'Enfermedad periodontal severa',
      'Neoplasias (linfoma)',
    ],
    diagnosis: {
      clinicalExam: 'Estomatitis, infecciones recurrentes, linfadenopatía, estado corporal deteriorado.',
      labTests: [
        'ELISA para anticuerpos FIV (screening)',
        'Western Blot para confirmación',
        'PCR para ADN proviral',
        'Hemograma: puede ser normal o leucopenia',
        'Química: hiperglobulinemia policlonal',
      ],
      imaging: [
        'Radiografía dental: reabsorción dental',
      ],
      differentialDiagnosis: [
        'FeLV',
        'Enfermedad dental primaria',
        'Estomatitis linfocítica-plasmocítica',
      ],
    },
    treatment: {
      firstLine: [
        'Manejo de infecciones secundarias',
        'Antibióticos según cultivo',
        'Alimentación de alta calidad',
        'Antivirales: AZT (Zidovudina) 5 mg/kg PO q12h',
        'Tratamiento de estomatitis: poliquimioterapia',
        'Interferón omega recombinante',
      ],
      secondLine: [
        'Inmunomoduladores: Poliferrina de dextrano',
        'Extracción dental agresiva para estomatitis',
        'Corticoides tópicos bucales',
      ],
      emergency: 'Infección oportunista severa: hospitalización + antibióticos IV.',
      duration: 'Manejo de por vida. Fase latente puede durar años.',
    },
    prevention: [
      'No hay vacuna',
      'Mantener gatos en interiores',
      'Castrar machos (reduce agresividad y mordeduras)',
      'Test FIV antes de integrar nuevos gatos',
      'Evitar contacto con gatos callejeros',
    ],
    prognosis: 'guarded',
    isZoonotic: false,
    references: [
      'Levy J, et al. Feline Immunodeficiency Virus Infection. In: Greene CE, ed. 4th ed. Elsevier; 2012.',
      'AAFP - FIV Testing Guidelines',
    ],
  },
  {
    id: 'cat-fip',
    name: 'Peritonitis Infecciosa Felina',
    scientificName: 'Feline Infectious Peritonitis (FIP)',
    species: 'cat',
    category: 'infectious',
    severity: 'critical',
    description: 'Enfermedad inmunomediada causada por una mutación del coronavirus enterico felino (FCoV). Forma húmeda (efusiva) o seca (granulomatosa). Frecuente en gatos jóvenes de colonias multi-gato.',
    keySigns: [
      'Forma húmeda: acumulación de líquido abdominal o torácico amarillo-viscoso',
      'Fiebre persistente no响应 a antibióticos',
      'Pérdida de peso progresiva',
      'Anorexia',
      'Letargia',
      'Forma seca: signos neurológicos (ataxia, nistagmo)',
      'Forma seca: signos oculares (uveítis, fibrina en cámara anterior)',
      'Hepatomegalia',
      'Ictericia',
    ],
    diagnosis: {
      clinicalExam: 'Líquido ascítico amarillo-dorado, viscosity, fiebre, hepatomegalia.',
      labTests: [
        'Análisis de líquido ascítico: alta viscosidad, proteína >3.5 g/dL, Rivalta positiva',
        'Citología del líquido: exudato no degenerativo, macrófagos',
        'PCR en líquido o tejido para FCoV',
        'Serología FCoV (no diagnóstica por sí sola)',
        'Hemograma: anemia, linfopenia, hiperglobulinemia',
        'Química: elevación de AGP (alfa-1 ácido glicoproteína)',
      ],
      imaging: [
        'Radiografía torácica: effusión pleural',
        'Ecografía abdominal: líquido libre, masas granulomatosas',
      ],
      differentialDiagnosis: [
        'Carcinomatosis',
        'Linfa',
        'Insuficiencia cardíaca congestiva',
        'Peritonitis',
      ],
    },
    treatment: {
      firstLine: [
        'GS-441524 (antiviral oral) - nuevo tratamiento revolucionario',
        'Protocolo de 84 días con GS-441524',
        'Dosis: 4-6 mg/kg SC q24h',
        'Supportivo: fluidoterapia, nutrición',
        'Drainaje de líquido si dificultad respiratoria',
      ],
      secondLine: [
        'GC376 (inhibidor de proteasa)',
        'Prednisona 1-2 mg/kg PO (terapia inmunosupresora)',
        'Famotidina 1 mg/kg PO q12h',
        'Vitaminas y suplementos',
      ],
      emergency: 'Dificultad respiratoria por effusión: toracocentesis de emergencia.',
      duration: 'Tratamiento GS-441524: 84 días. Tasa de curación >80% con tratamiento temprano.',
    },
    prevention: [
      'Higiene estricta en colonias',
      'Reducción del estrés (espacio, enriquecimiento ambiental)',
      'Cepillos de pelo individuales',
      'Separar gatitos del grupo al primer signo',
      'Evitar colonias superpobladas',
    ],
    prognosis: 'poor',
    isZoonotic: false,
    references: [
      'Pedersen NC, et al. Efficacy and Safety of GS-441524 for Treatment of Cats with FIP. J Feline Med Surg. 2019.',
      'ACVFIP - FIP Treatment Guidelines',
    ],
  },
  {
    id: 'cat-calici',
    name: 'Calicivirus Felino',
    scientificName: 'Feline Calicivirus (FCV)',
    species: 'cat',
    category: 'infectious',
    severity: 'moderate',
    description: 'Infección viral respiratoria altamente contagiosa. Causa úlceras orales, secreción nasal y conjuntival. Especies altamente variable con potencial pandémico.',
    keySigns: [
      'Úlceras en lengua, paladar y nariz',
      'Secreción nasal serosa a mucopurulenta',
      'Conjuntivitis bilateral',
      'Fiebre',
      'Inapetencia (por dolor oral)',
      'Babeo',
      'Cojera en gatitos (poliartritis)',
      'Raramente: pneumonia',
    ],
    diagnosis: {
      clinicalExam: 'Úlceras linguales patognomónicas, secreción nasal, fiebre.',
      labTests: [
        'PCR en hisopo orofaringeo/conjuntival',
        'Aislamiento viral',
        'Citología de úlceras',
      ],
      imaging: [],
      differentialDiagnosis: [
        'Herpesvirus (rinotraqueítis)',
        'Estomatitis',
        'Cuerpo extraño oral',
      ],
    },
    treatment: {
      firstLine: [
        'Soporte: fluidoterapia si deshidratación',
        'Antibióticos para infecciones secundarias: Amoxicilina-ácido clavulánico',
        'Analgesia: Buprenorfina 0.02 mg/kg PO q8-12h',
        'Alimento de textura suave o líquido',
        'Nebulización si congestión nasal',
        'Vitaminas del complejo B',
      ],
      secondLine: [
        'Interferón omega',
        'Antivirales: Famciclovir 40-90 mg/kg PO q8-12h',
      ],
      emergency: 'Pneumonia viral: oxigenoterapia, antibióticos IV.',
      duration: '7-14 días. Portadores crónicos pueden ser fuente de infección.',
    },
    prevention: [
      'Vacunación: vacuna intranasal u oral a partir de 8 semanas',
      'Refuerzo anual',
      'Aislamiento de gatos enfermos',
      'Desinfección de superficies (hipoclorito de sodio)',
    ],
    prognosis: 'good',
    isZoonotic: false,
    references: [
      'Radford AD, et al. Feline Calicivirus Infection. In: Greene CE, ed. 4th ed. Elsevier; 2012.',
    ],
  },
  {
    id: 'cat-hcm',
    name: 'Cardiomiopatía Hipertrófica',
    scientificName: 'Hypertrophic Cardiomyopathy (HCM)',
    species: 'cat',
    category: 'cardiovascular',
    severity: 'severe',
    description: 'Enfermedad cardíaca más común en gatos. Engrosamiento asimétrico del miocardio ventricular izquierdo. Predisposición genética en Maine Coon, Ragdoll, British Shorthair.',
    keySigns: [
      'Disnea (dificultad respiratoria)',
      'Taquicardia o arritmia',
      'Intolerancia al ejercicio',
      'Soplo cardíaco sistólico (no siempre presente)',
      'Galope S3 o S4',
      'Tromboembolismo de aorta terminal (síndrome de parálisis bilateral)',
      'Muerte súbita',
    ],
    diagnosis: {
      clinicalExam: 'Soplo sistólico (grade I-IV/VI), galope, frecuencia cardíaca anormal.',
      labTests: [
        'NT-proBNP o Troponina I: marcadores de enfermedad cardíaca',
        'ECG: arritmias, hipertrofia ventricular izquierda',
        'Hemograma y química: baseline',
      ],
      imaging: [
        'Ecocardiografía DOPPLER: Gold standard. Medición de pared IV y septo IV',
        'Radiografía torácica: cardiomegalia, patrón venoso pulmonar',
      ],
      differentialDiagnosis: [
        'Hipertiroidismo',
        'Hipertensión sistémica',
        'Cardiomiopatía dilatada',
        'Pericarditis constrictiva',
      ],
    },
    treatment: {
      firstLine: [
        'Furosemida 1-2 mg/kg PO q12-24h (si signos de congestión)',
        'Atenolol 6.25-12.5 mg PO q12h (si taquicardia sin insuficiencia)',
        'Clopidogrel 18.75 mg PO q24h (prevención de ATE)',
        'Tiroxina bajas dosis si hipertiroidismo concomitante',
        'Oxigenoterapia si disnea',
        'Restricción de ejercicio',
      ],
      secondLine: [
        'Enalapril 0.5 mg/kg PO q12-24h (si insuficiencia cardíaca)',
        'Pimobendan 0.25-0.3 mg/kg PO q12h',
        'Espironolactona 1-2 mg/kg PO q24h',
      ],
      emergency: 'Tromboembolismo de aorta terminal: heparina + analgesia + soporte. Pronóstico reservado.',
      duration: 'Tratamiento de por vida. Monitoreo ecográfico cada 3-6 meses.',
    },
    prevention: [
      'Screening genético en razas predisuestas',
      'Ecocardiografía preventiva antes de reproducción',
      'Control de dieta: sodio moderado, taurina adecuada',
      'Evitar estrés',
    ],
    prognosis: 'guarded',
    isZoonotic: false,
    references: [
      'Trepanier LA. Feline Hypertrophic Cardiomyopathy. Vet Clin North Am Small Anim Pract. 2017.',
      'ACVIM - Feline Cardiomyopathy Guidelines',
    ],
  },
  {
    id: 'cat-cr',
    name: 'Enfermedad Renal Crónica Felina',
    scientificName: 'Chronic Kidney Disease (CKD) Feline',
    species: 'cat',
    category: 'renal',
    severity: 'moderate',
    description: 'Enfermedad degenerativa progresiva del riñón, la causa más común de muerte en gatos geriátricos. IRIS staging I-IV. Los gatos pierden función renal gradualmente.',
    keySigns: [
      'Polidipsia y poliuria',
      'Pérdida de peso',
      'Pelo deteriorado (seco, sin brillo)',
      'Anorexia',
      'Vómitos',
      'Halitosis urémica',
      'Depresión',
      'Úlceras bucales',
      'Piel seca y elástica (deshidratación)',
    ],
    diagnosis: {
      clinicalExam: 'Pérdida de peso, deshidratación, riñones palpablemente pequeños o irregulares.',
      labTests: [
        'Creatinina elevada en 2 muestras (>1.6 mg/dL)',
        'SDMA >18 µg/dL',
        'Análisis de orina: isostenuria, proteinuria',
        'UPC >0.4 (proteinuria)',
        'Fosfatasa alcalina elevada',
        'Electrolitos alterados',
        'Anemia normocítica',
      ],
      imaging: [
        'Ecografía renal: tamaño reducido, irregularidad cortical',
        'Radiografía abdominal',
      ],
      differentialDiagnosis: [
        'Enfermedad renal aguda',
        'Nefropatía por amiloidosis',
        'Pielonefritis',
      ],
    },
    treatment: {
      firstLine: [
        'Dieta renal (Hills k/d, Royal Canin Renal)',
        'Suplementación con EPA/DHA (omega-3)',
        'Fosfato de aluminio si hiperfosfatemia',
        'Fluidoterapia subcutánea en casa',
        'EPO si anemia (Hct <25%)',
        'Antiéméticos: Maropitant',
      ],
      secondLine: [
        'Telmisartán para proteinuria',
        'Calcitriol',
        'Probióticos renales',
      ],
      emergency: 'Crisis urémica: fluidoterapia IV, diálisis peritoneal.',
      duration: 'Manejo de por vida.',
    },
    prevention: [
      'Hidratación adecuada (fuentes de agua, comida húmeda)',
      'Dieta de calidad',
      'Evitar nefrotóxicos (AINEs, aminoglucósidos)',
      'Screening anual en gatos >7 años',
    ],
    prognosis: 'guarded',
    isZoonotic: false,
    references: [
      'IRIS - Staging CKD in Cats',
      'Elli J, et al. Chronic Kidney Disease in Cats. J Feline Med Surg. 2020.',
    ],
  },
  {
    id: 'cat-hyperthyroid',
    name: 'Hipertiroidismo',
    scientificName: 'Hyperthyroidism Feline',
    species: 'cat',
    category: 'endocrine',
    severity: 'moderate',
    description: 'Producción excesiva de hormonas tiroideas, generalmente por adenoma benigno. La enfermedad endocrina más común en gatos mayores (>7 años).',
    keySigns: [
      'Pérdida de peso a pesar de apetito voraz',
      'Poliuria y polidipsia',
      'Hiperactividad, irritabilidad',
      'Taquicardia, soplo cardíaco',
      'Vómitos y diarrea',
      'Pelo descuidado, grasiento',
      'Masa cervical palpable (glándula tiroides)',
      'Aumento de volumen muscular',
    ],
    diagnosis: {
      clinicalExam: 'Masa cervical, taquicardia, pérdida de peso, tiroides palpable.',
      labTests: [
        'T4 total: elevada (>4.5 µg/dL)',
        'T4 libre por equilibrio dialítico',
        'Hemograma: puede haber eritrocitosis leve',
        'Química: elevación de ALT, AST, fosfatasa alcalina',
        'Perfil tiroideo completo si T4 borderline',
      ],
      imaging: [
        'Ecografía tiroidea',
        'Radiografía torácica: cardiomegalia',
      ],
      differentialDiagnosis: [
        'Diabetes mellitus',
        'Insuficiencia renal',
        'Neoplasia gastrointestinal',
      ],
    },
    treatment: {
      firstLine: [
        'Metimazol (Tapazol) 2.5-5 mg PO q12-24h',
        'Dosis inicial: 2.5 mg PO q12h, ajustar según T4',
        'Methimazol tópico en oreja',
        'Cardiomiopatía pre-existente: estabilizar primero',
      ],
      secondLine: [
        'Yodo radioactivo (I-131): tratamiento definitivo',
        'Cirugía de tiroidectomía',
        'Dieta tiroidea (Hills y/d)',
      ],
      emergency: 'Crisis tirotóxica: β-bloqueantes (Atenolol), fluidoterapia, Metimazol IV.',
      duration: 'Metimazol: 1-4 semanas para efecto. T4 cada 3-6 meses. I-131: curación en 95%.',
    },
    prevention: [
      'No hay prevención conocida',
      'Screening de T4 anual en gatos >7 años',
      'Evitar dietas con suplementos de yodo excesivo',
    ],
    prognosis: 'excellent',
    isZoonotic: false,
    references: [
      'Peterson ME. Hyperthyroidism in Cats. In: Ettinger SJ, ed. 8th ed. Elsevier; 2017.',
      'AAFP - Hyperthyroidism in Cats Guidelines',
    ],
  },
  {
    id: 'cat-urinary',
    name: 'Síndrome Urológico Felino (FLUTD)',
    scientificName: 'Feline Lower Urinary Tract Disease',
    species: 'cat',
    category: 'renal',
    severity: 'severe',
    description: 'Conjunto de trastornos del tracto urinario inferior que causan disuria, estranguria y hematuria. Incluye cistitis idiopática, urolitiasis, obstrucción uretral (especialmente machos).',
    keySigns: [
      'Esfuerzo para orinar (estranguria)',
      'Orina en pequeñas cantidades o anuria',
      'Hematuria (sangre en orina)',
      'Lamido frecuente de zona genital',
      'Orinar fuera del arenero',
      'Vocalización al orinar',
      'Obstrucción uretral (machos): abdomen distendido, dolor severo',
      'Letargia, anorexia',
    ],
    diagnosis: {
      clinicalExam: 'Vejiga palpable dura (obstrucción), dolor abdominal, deshidratación.',
      labTests: [
        'Análisis de orina: cristales (struvita, oxalato de calcio), hematuria, piuria',
        'Urocultivo: descartar infección bacteriana',
        'Química: elevación de BUN, creatinina si obstrucción',
        'Electrolitos: hiperpotasemia potencialmente mortal',
      ],
      imaging: [
        'Radiografía abdominal: urolitos visibles',
        'Ecografía vesical: cálculos, mucosidad',
      ],
      differentialDiagnosis: [
        'Cistitis bacteriana',
        'Cistitis idiopática felina',
        'Neoplasia vesical',
        'Uretritis',
      ],
    },
    treatment: {
      firstLine: [
        'Desobstrucción uretral: cateterización bajo sedación/anestesia',
        'Fluidoterapia IV agresiva (corrección de hiperpotasemia)',
        'Gluconato de calcio si hiperpotasemia severa',
        'Gluconato de sodio + insulina + dextrosa',
        'Dieta urinaria (Hills c/d, Royal Canin Urinary)',
        'Cystocap (N-acetilcisteína) si cistitis',
        'Antibióticos solo si infección documentada',
      ],
      secondLine: [
        'Cistocentesis quirúrgica si cateterismo fallido',
        'Perineostomía si obstrucciones recurrentes',
        'Ansiolíticos: Gabapentina, Amitriptilina',
      ],
      emergency: 'OBSTRUCCIÓN URETRAL: EMERGENCIA. Desobstrucción inmediata. Riesgo de muerte por hiperpotasemia.',
      duration: 'Dietoterapia de por vida. Monitoreo de orina cada 1-3 meses.',
    },
    prevention: [
      'Dieta urinaria húmeda (aumenta ingesta de agua)',
      'Fuentes de agua fresca (bebederos con flujo)',
      'Areneros limpios y abundantes',
      'Reducción de estrés (enriquecimiento ambiental)',
      'Mantenimiento de peso ideal',
      'Purificadores de agua',
    ],
    prognosis: 'guarded',
    isZoonotic: false,
    references: [
      'WSAVA - Feline Lower Urinary Tract Disease Guidelines',
      'APCC - Nutritional Management of FLUTD',
    ],
  },
  {
    id: 'cat-dermatophytosis',
    name: 'Dermatofitosis (Tiña)',
    scientificName: 'Dermatophytosis (Microsporum canis)',
    species: 'cat',
    category: 'dermatological',
    severity: 'mild',
    description: 'Infección fúngica de la piel, pelo y uñas causada por dermatofitos. M. canis causa el 98% de los casos en gatos. Enfermedad zoonótica.',
    keySigns: [
      'Lesiones circulares alopecicas (redondas, sin pelo)',
      'Costras y escamas',
      'Eritema periférico',
      'Pérdida de pelo en parches',
      'Picazón variable (puede no prurir)',
      'Anillos de crecimiento en cultivo',
      'Lesiones en orejas, cara, patas',
      'Uñas quebradizas (onicodistrofia)',
    ],
    diagnosis: {
      clinicalExam: 'Lesiones alopecicas redondeadas, costras, distribución en cara y patas.',
      labTests: [
        'Lámpara de Wood: fluorescencia verde-amarilla (solo 50% de M. canis)',
        'Raspado de piel + KOH: hifas y microconidias',
        'Cultivo en agar Sabouraud o DTM: resultados en 7-21 días',
        'PCR para especie de dermatofito',
      ],
      imaging: [],
      differentialDiagnosis: [
        'Dermatitis alérgica',
        'Sarna',
        'Dermatitis miliar',
        'Alopecia psicogénica',
      ],
    },
    treatment: {
      firstLine: [
        'Itraconazol 5 mg/kg PO q24h con comida grasa por 6-8 semanas',
        'Terbinafina 30 mg/kg PO q24h por 6 semanas',
        'Shampoo con clorhexidina/miconazol 2 veces por semana',
        'Limpiar ambiente: lavar camas, aspirar',
        'Tratar todos los gatos del hogar',
      ],
      secondLine: [
        'Enilconazol tópico (rinse)',
        'Micafungina',
        'Vacuna (disponibilidad variable)',
      ],
      duration: 'Hasta 2 cultivos negativos consecutivos. Promedio 6-8 semanas.',
    },
    prevention: [
      'Aislamiento de gatos infectados',
      'Desinfección del ambiente',
      'Exámenes dermatológicos regulares',
      'Buen estado nutricional e inmune',
    ],
    prognosis: 'excellent',
    isZoonotic: true,
    references: [
      'Moriello KA, et al. Dermatophytosis in Cats. In: Greene CE, ed. 4th ed. Elsevier; 2012.',
      'AAFP - Dermatophytosis Guidelines',
    ],
  },
  {
    id: 'cat-obesity',
    name: 'Obesidad',
    scientificName: 'Feline Obesity',
    species: 'cat',
    category: 'nutritional',
    severity: 'moderate',
    description: 'Acumulación excesiva de grasa corporal. Más del 60% de gatos domésticos están con sobrepeso u obesos. Predisone a diabetes, enfermedad articular, hepática y urinaria.',
    keySigns: [
      'IMC >30% sobre peso ideal',
      'Pérdida de definición de cintura',
      'Grasa palpable sobre costillas, columna, abdomen',
      'Dificultad para aseo dorsal',
      'Intolerancia al ejercicio',
      'Dolor articular (artritis)',
      'Respiración ruidosa',
    ],
    diagnosis: {
      clinicalExam: 'Evaluación de condición corporal (BCS 1-9). Peso ideal según raza.',
      labTests: [
        'Hemograma y química: baseline',
        'Perfil lipídico',
        'Glucosa y fructosamina: descartar diabetes',
      ],
      imaging: [],
      differentialDiagnosis: [
        'Hipertiroidismo (pérdida de peso)',
        'Diabetes mellitus',
      ],
    },
    treatment: {
      firstLine: [
        'Dieta de reducción calórica: -20% de calorías de mantenimiento',
        'Dieta rica en proteína, baja en carbohidratos',
        'Alimentación fraccionada (3-4 comidas/día)',
        'Ejercicio enriquecido: juguetes interactivos, sesiones de juego',
        'Meta-analysis: pérdida de 1-2% del peso corporal por semana',
      ],
      secondLine: [
        'Hills metabolic diet',
        'Péptidos de saciedad',
        'Probióticos para control de peso',
      ],
      emergency: 'Lipidosis hepática si anorexia >48h: soporte nutricional urgente.',
      duration: 'Programa de pérdida de peso: 3-6 meses. Mantenimiento de por vida.',
    },
    prevention: [
      'Control de porciones desde cachorro',
      'Ejercicio diario interactivo',
      'Evitar sobras de comida humana',
      'Medir el peso mensualmente',
      'Dietas formuladas para vida interior',
    ],
    prognosis: 'good',
    isZoonotic: false,
    references: [
      'German AJ. The Growing Problem of Obesity in Dogs and Cats. J Nutr. 2006.',
      'AAHA - Weight Management Guidelines',
    ],
  },
  {
    id: 'cat-asthma',
    name: 'Asma Felino',
    scientificName: 'Feline Asthma / Feline Bronchial Disease',
    species: 'cat',
    category: 'respiratory',
    severity: 'moderate',
    description: 'Enfermedad alérgica/inflamatoria de las vías aéreas inferiores. Episodios de broncoespasmo recurrentes. Similar al asma humano. Predisposición en gatos jóvenes.',
    keySigns: [
      'Episodios de tos seca paroxística',
      'Disnea expiratoria (boca abierta)',
      'Respiración abdominal',
      'Postura agachada con cuello extendido',
      'Cianosis en episodios severos',
      'Vómitos asociados a tos',
      'Intolerancia al ejercicio',
    ],
    diagnosis: {
      clinicalExam: 'Respiración abdominal, crepitantes, sibilancias a la auscultación.',
      labTests: [
        'Hemograma: eosinofilia (no siempre)',
        'Citología de lavado broncoalveolar: eosinófilos >50%',
        'Radiografía torácica: patrón broncointersticial',
      ],
      imaging: [
        'Radiografía torácica: ensanchamiento de bronquios',
        'Broncoscopia: evaluación de vías aéreas',
      ],
      differentialDiagnosis: [
        'Enferadad pulmonar parasitaria',
        'Bronquitis crónica',
        'Insuficiencia cardíaca congestiva',
        'Neumonía',
      ],
    },
    treatment: {
      firstLine: [
        'Prednisolona 1-2 mg/kg PO q12-24h (antiinflamatorio)',
        'Terbutalina 0.01-0.2 mg/kg PO q8-12h (broncodilatador)',
        'Dexametasona inhalada con spacer (FeliCort)',
        'Evitar alérgenos ambientales (humo, perfumes, polvo)',
      ],
      secondLine: [
        'Ciclosporina 5 mg/kg PO q24h',
        'Metotrexato',
        'Desensibilización alérgena',
      ],
      emergency: 'Broncoespasmo agudo severo: oxigenoterapia, corticoides IV, terbutalina SC.',
      duration: 'Manejo de por vida. Reducción gradual de corticoides.',
    },
    prevention: [
      'Evitar alérgenos (humo, aerosoles, polvo de arena)',
      'Arenero libre de polvo (cristales de sílice)',
      'Ambiente limpio y libre de irritantes',
      'Humidificador si ambiente seco',
    ],
    prognosis: 'good',
    isZoonotic: false,
    references: [
      'Levy LR, et al. Feline Asthma. In: Ettinger SJ, ed. 8th ed. Elsevier; 2017.',
    ],
  },
  {
    id: 'cat-dentalresorption',
    name: 'Reabsorción Dental',
    scientificName: 'Feline Odontoclastic Resorptive Lesions (FORL)',
    species: 'cat',
    category: 'dental',
    severity: 'moderate',
    description: 'Destrucción progresiva del diente por odontoclastos. Afecta al 28-67% de gatos. Tipo I (con enfermedad periodontal) y Tipo II (sin inflamación periodontal).',
    keySigns: [
      'Dolor oral al comer',
      'Babeo',
      'Rechazo de alimento seco',
      'Sangrado de encías',
      'Fractura dental espontánea',
      'Lesiones rosadas en línea de la encía',
      'Halitosis',
      'Comportamiento defensivo al manipular cabeza',
    ],
    diagnosis: {
      clinicalExam: 'Lesiones rosadas en unión cemento-encía, fracturas dentales, sarro.',
      labTests: [],
      imaging: [
        'Radiografías dentales intraorales: lesión radiolúcida en diente',
        'CLASIFICACIÓN: Tipo I (raíz visible) vs Tipo II (raíz reabsorbida)',
      ],
      differentialDiagnosis: [
        'Enfermedad periodontal',
        'Fractura dental traumática',
        'Neoplasia oral',
      ],
    },
    treatment: {
      firstLine: [
        'Extracción dental completa (tratamiento de elección)',
        'Extracción de raíz residual si Tipo II',
        'Tratamiento periodontal concomitante',
        'Analgesia post-operatoria: Buprenorfina + Meloxicam',
      ],
      secondLine: [
        'Corona dental (controversial, solo Tipo II sin exposición pulpar)',
        'Odontectomía parcial',
      ],
      emergency: 'Dolor severo: analgesia multimodal inmediata.',
      duration: 'Extracción: recuperación 7-10 días. Seguimiento dental anual.',
    },
    prevention: [
      'Exámenes dentales anuales con radiografías',
      'Cepillado dental regular (limitado efecto)',
      'Dieta húmeda reduce estrés mecánico',
      'Detección temprana con radiografías',
    ],
    prognosis: 'good',
    isZoonotic: false,
    references: [
      'Gorrel C. Tooth Resorption in Cats. In: Veterinary Dentistry for the General Practitioner. Elsevier; 2013.',
      'AVDC - FORL Guidelines',
    ],
  },
  {
    id: 'cat-toxoplasmosis',
    name: 'Toxoplasmosis',
    scientificName: 'Toxoplasma gondii',
    species: 'cat',
    category: 'parasitic',
    severity: 'moderate',
    description: 'Enfermedad parasitaria causada por el protozoo Toxoplasma gondii. El gato es el hospedador definitivo. La mayoría de gatos infectados son asintomáticos pero eliminan oocistos en heces.',
    keySigns: [
      'Fiebre',
      'Pérdida de peso',
      'Letargia',
      'Mialgias',
      'Dificultad respiratoria (neumonitis)',
      'Signos neurológicos: convulsiones, ataxia, cambios de comportamiento',
      'Ictericia (hepatitis)',
      'Aborto en gatas gestantes',
      'Ojo rojo (uveítis)',
    ],
    diagnosis: {
      clinicalExam: 'Fiebre, mialgias, neurológicos, uveítis.',
      labTests: [
        'Serología IgG e IgM: IgM aguda >1:64, IgG >1:1024',
        'PCR en heces, sangre, LCR, humor acuoso',
        'Oocistos en heces (flotación fecal)',
        'Hemograma: linfocitosis o neutropenia',
      ],
      imaging: [
        'Radiografía torácica si neumonitis',
        'MRI/TC craneal si signos neurológicos',
      ],
      differentialDiagnosis: [
        'FIP',
        'FeLV/FIV',
        'Encefalitis infecciosa',
        'Neoplasia',
      ],
    },
    treatment: {
      firstLine: [
        'Clindamicina 12.5-25 mg/kg PO q12h por 2-4 semanas',
        'Ponamicina 5 mg/kg PO q12h',
        'Doxiciclina 10 mg/kg PO q12h',
        'Trimetoprim-sulfametoxazol 15 mg/kg PO q12h',
        'Soporte nutricional',
      ],
      secondLine: [
        'Ponarizol (antiinflamatorio)',
        'Prednisona si uveítis severa',
      ],
      emergency: 'Encefalitis aguda: hospitalización + antibióticos IV.',
      duration: '2-4 semanas de tratamiento. Oocistas en heces: 1-2 semanas.',
    },
    prevention: [
      'Cocinar carne thoroughly antes de alimentar',
      'Evitar caza cruda',
      'Limpiar arenero diariamente (oocistas maduran 24-48h)',
      'Lavarse las manos después de limpiar arenero',
      'Gestantes: evitar limpiar areneros',
    ],
    prognosis: 'good',
    isZoonotic: true,
    references: [
      'Dubey JP, et al. Toxoplasmosis in Cats. In: Greene CE, ed. 4th ed. Elsevier; 2012.',
      'CDC - Toxoplasmosis in Cats',
    ],
  },
  {
    id: 'cat-rhinotracheitis',
    name: 'Rinotraqueítis Felina',
    scientificName: 'Feline Herpesvirus-1 (FHV-1)',
    species: 'cat',
    category: 'infectious',
    severity: 'moderate',
    description: 'Infección viral respiratoria causada por herpesvirus tipo 1. Principal causa de enfermedad respiratoria felina. Infección latente con reactivación durante estrés.',
    keySigns: [
      'Estornudos frecuentes',
      'Secreción nasal profusa (serosa a mucopurulenta)',
      'Conjuntivitis bilateral severa',
      'Queratitis dendrítica (úlceras corneales)',
      'Fiebre',
      'Inapetencia',
      'Ulceración nasal y oral',
      'Blefaroespasmo',
    ],
    diagnosis: {
      clinicalExam: 'Conjuntivitis severa, queratitis dendrítica, úlceras nasales.',
      labTests: [
        'PCR en hisopo nasal/conjuntival',
        'Citología: células multinucleadas con inclusión intranuclear',
        'Aislamiento viral (poco práctico)',
      ],
      imaging: [],
      differentialDiagnosis: [
        'Calicivirus',
        'Chlamydia felis',
        'Bordetella bronchiseptica',
        'Cuerpo extraño nasal',
      ],
    },
    treatment: {
      firstLine: [
        'Famciclovir 90 mg/kg PO q8-12h (antiviral de elección)',
        'Gotas oculares: Cidofovir tópico q6h',
        'Nebulización con solución salina',
        'Vitaminas del complejo B',
        'Antibióticos tópicos para infecciones secundarias',
        'Nutrición suave y caliente para estimular apetito',
      ],
      secondLine: [
        'L-lisina 500 mg PO q12h (controversial)',
        'Interferón omega tópico/ocular',
        'Interferón alfa recombinante',
      ],
      emergency: 'Úlceras corneales profundas: oftalmólogo urgente.',
      duration: 'Signos agudos: 7-14 días. Portadores latentes: de por vida.',
    },
    prevention: [
      'Vacunación intranasal u parenteral',
      'Higiene en guarderías',
      'Reducción de estrés',
      'Aislamiento de gatos enfermos',
    ],
    prognosis: 'good',
    isZoonotic: false,
    references: [
      'Thiry E, et al. Feline Herpesvirus Infection. In: Greene CE, ed. 4th ed. Elsevier; 2012.',
    ],
  },
];

export const ALL_DISEASES: Disease[] = [...DOG_DISEASES, ...CAT_DISEASES];

export const SPECIES_INFO = {
  dog: { label: 'Perro', icon: 'dog', color: '#4CAF50' },
  cat: { label: 'Gato', icon: 'cat', color: '#FF9800' },
  both: { label: 'Ambos', icon: 'paw', color: '#2196F3' },
} as const;

export { DISEASE_CATEGORIES, DOG_DISEASES, CAT_DISEASES };
