export const MEDICATION_CATEGORIES = [
  { key: 'intraoperatorio', label: 'Intraoperatorios', icon: 'syringe' as const, color: '#E53935' },
  { key: 'receta', label: 'Receta', icon: 'prescription' as const, color: '#1E88E5' },
] as const;

export type MedicationCategory = typeof MEDICATION_CATEGORIES[number]['key'];

// ─────────────────────────────────────────────────────────
// Especialidades del vademécum
// ─────────────────────────────────────────────────────────

export interface Especialidad {
  key: string;
  label: string;
  icon: string;
  color: string;
}

export const ESPECIALIDADES: Especialidad[] = [
  { key: 'todas', label: 'Todas', icon: 'LayoutGrid', color: '#546E7A' },
  { key: 'analgesia', label: 'Analgesia', icon: 'Heart', color: '#E53935' },
  { key: 'antibioticos', label: 'Antibióticos', icon: 'Shield', color: '#1565C0' },
  { key: 'antiinflamatorios', label: 'Antiinflamatorios', icon: 'Flame', color: '#558B2F' },
  { key: 'antiparasitarios', label: 'Antiparasitarios', icon: 'Bug', color: '#00838F' },
  { key: 'cardiologia', label: 'Cardiología', icon: 'HeartPulse', color: '#AD1457' },
  { key: 'dermatologia', label: 'Dermatología', icon: 'Sparkles', color: '#6A1B9A' },
  { key: 'endocrinologia', label: 'Endocrinología', icon: 'Activity', color: '#EF6C00' },
  { key: 'gastroenterologia', label: 'Gastroenterología', icon: 'Stethoscope', color: '#00695C' },
  { key: 'intraoperatorios', label: 'Intraoperatorios', icon: 'Syringe', color: '#B71C1C' },
  { key: 'neurologia', label: 'Neurología', icon: 'Brain', color: '#1976D2' },
  { key: 'oftalmologia', label: 'Oftalmología', icon: 'Eye', color: '#F57F17' },
  { key: 'oncologia', label: 'Oncología', icon: 'Ribbon', color: '#4527A0' },
  { key: 'respiratorio', label: 'Respiratorio', icon: 'Wind', color: '#2E7D32' },
  { key: 'urologia', label: 'Urología', icon: 'Droplets', color: '#D84315' },
];

export const getEspecialidadByKey = (key: string): Especialidad | undefined =>
  ESPECIALIDADES.find(e => e.key === key);

// ─────────────────────────────────────────────────────────
// Colores de familia (se mantienen para intraoperatorios)
// ─────────────────────────────────────────────────────────

export const FAMILIA_COLORS: Record<string, string> = {
  'Opioide': '#E53935',
  'Agonista sintético mu puro / antagonista NMDA': '#C62828',
  'Agonista kappa / antagonista mu': '#D32F2F',
  'Agonista natural mu puro': '#B71C1C',
  'Agonista sintético mu puro potente': '#FF1744',
  'Benzodiacepina de acción rápida': '#7B1FA2',
  'Benzodiacepina clásica': '#6A1B9A',
  'Fenotiacina': '#4527A0',
  'Agonista alfa-2 adrenérgico (alta selectividad)': '#1565C0',
  'Agonista alfa-2 adrenérgico (baja selectividad)': '#1976D2',
  'Anestésico disociativo (derivado fenciclidina)': '#00838F',
  'Fenol / hipnótico de acción ultracorta': '#00695C',
  'Simpaticomimético endógeno pan-adrenérgico': '#EF6C00',
  'Anticolinérgico derivado belladónico': '#F57F17',
  'Simpaticomimético alfa-1 dominante': '#E65100',
  'Catecolamina endógena simpaticomimética': '#D84315',
  'Simpaticomimético de acción mixta': '#BF360C',
  'Agonista alfa-1 puro': '#FF6D00',
  'Amina catecolamínica beta-1 selectiva': '#FF9100',
  'Anestésico local': '#2E7D32',
  'Anestésico disociativo': '#00897B',
  'AINE': '#558B2F',
  'Antagonista NK1': '#AD1457',
  // Nuevas familias de las especialidades
  'Penicilina de amplio espectro': '#1565C0',
  'Penicilina + inhibidor beta-lactamasa': '#1976D2',
  'Cefalosporina de 1ª generación': '#0D47A1',
  'Cefalosporina de 3ª generación': '#1565C0',
  'Cefalosporina de 3ª generación de acción prolongada': '#1976D2',
  'Cefalosporina de 3ª generación de amplio espectro': '#0D47A1',
  'Fluoroquinolona de amplio espectro': '#00838F',
  'Fluoroquinolona': '#0097A7',
  'Fluoroquinolona de 4ª generación': '#006064',
  'Tetraciclina de amplio espectro': '#558B2F',
  'Nitroimidazol': '#689F38',
  'Lincosamida': '#7CB342',
  'Macrólido de amplio espectro': '#8BC34A',
  'Amfenicol de amplio espectro': '#9CCC65',
  'Sulfonamida + inhibidor de la dihidrofolato reductasa': '#AED581',
  'Aminoglucósido': '#C0CA33',
  'Inhibidor de anhidrasa carbónica tópico': '#F57F17',
  'Corticoesteroide tópico': '#FFA000',
  'Corticoesteroide tópico potente': '#FF8F00',
  'Aminoglucósido tópico': '#FF6F00',
  'Fluoroquinolona tópico': '#E65100',
  'Inmunosupresor tópico': '#6A1B9A',
  'Agonista muscarínico tópico': '#AD1457',
  'Inhibidor selectivo JAK (Janus quinasa)': '#7B1FA2',
  'Inmunosupresor (inhibidor de calcineurina)': '#9C27B0',
  'Antifúngico azólico': '#00897B',
  'Alilamina (antifúngico)': '#009688',
  'Triazol (antifúngico)': '#26A69A',
  'Análogo de purina (inmunosupresor)': '#4DB6AC',
  'Hormona tiroidea sintética (T4)': '#EF6C00',
  'Anititiroideo (inhibidor de peroxidasa tiroidea)': '#F57C00',
  'Insulina de acción intermedia': '#FB8C00',
  'Insulina de acción prolongada': '#FF9800',
  'Progestágeno': '#FFA726',
  'Antidepresivo tricíclico': '#7B1FA2',
  'Simpaticomimético (agonista alfa-1)': '#E65100',
  'Inhibidor de esteroidogenesis': '#D84315',
  'O,p\'-DDD (inhibidor corticosteroideo)': '#BF360C',
  'Análogo de ADH (hormona antidiurética)': '#FF7043',
  'Antagonista H2': '#00695C',
  'Gastroprotector (agente citoprotector)': '#00796B',
  'Inhibidor bomba de protones (H+/K+ ATPasa)': '#00897B',
  'Análogo de prostaglandina E1': '#009688',
  'Antagonista NK1 (antiemético)': '#AD1457',
  'Agonista D2 / antagonista 5-HT3': '#6A1B9A',
  'Antagonista 5-HT3': '#7B1FA2',
  'Agonista opioides periférico (mu)': '#880E4F',
  'Laxante osmótico': '#4E342E',
  'Barbitúrico de acción prolongada': '#1976D2',
  'Sales de bromuro (anticonvulsivante)': '#1565C0',
  'Análogo del ácido butírico (anticonvulsivante)': '#0D47A1',
  'Análogo del GABA (anticonvulsivante/neuropático)': '#00838F',
  'Benzodiacepina': '#7B1FA2',
  'Hidantoína (anticonvulsivante)': '#4527A0',
  'Derivado de iminostilbeno (anticonvulsivante)': '#311B92',
  'Antiviral con acción dopaminérgica': '#E65100',
  'Beta-2 agonista (broncodilatador)': '#2E7D32',
  'Metilxantina (broncodilatador)': '#388E3C',
  'Mucolítico (bromexina activo)': '#43A047',
  'Mucolítico (rompe puentes disulfuro)': '#4CAF50',
  'Corticoesteroide (glucocorticoide potente)': '#FF8F00',
  'Opioides (agonista mu débil)': '#880E4F',
  'Relajante muscular de acción directa': '#5D4037',
  'Farmacólogo urolítico': '#D84315',
  'Alcalinizante urinario': '#BF360C',
  'Desinfectante antiséptico': '#4E342E',
  'Antraciclina (antibiótico antineoplásico)': '#4527A0',
  'Platino (quimioterapéutico)': '#311B92',
  'Alquilante (quimioterapéutico)': '#1A237E',
  'Nitrosourea (quimioterapéutico)': '#283593',
  'Tirosina quinasa inhibidor (antineoplásico)': '#1565C0',
  'Análogo del ácido fólico (antimetabolito)': '#0D47A1',
  'Inhibidor de bomba de protones': '#00897B',
  'Corticoesteroide de acción intermedia (glucocorticoide)': '#FFA000',
  'Antihistamínico H1': '#7B1FA2',
  'Neuroesteroide / hipnótico': '#00838F',
  'Anestésico volátil halogenado': '#546E7A',
  'Anestésico volátil halogenado de baja solubilidad': '#607D8B',
  'Anticolinérgico sintético': '#F57F17',
  'Hormona peptídica vasoconstrictora': '#E65100',
  'Inhibidor de colinesterasa': '#D84315',
  'Bloqueador neuromuscular despolarizante': '#B71C1C',
  'Bloqueador neuromuscular no despolarizante (intermedio)': '#C62828',
  'Bloqueador neuromuscular no despolarizante de acción prolongada': '#D32F2F',
  'Antagonista opioide puro': '#880E4F',
  'Antagonista de benzodiacepinas': '#6A1B9A',
  'Benzodiacepina de acción intermedia': '#7B1FA2',
  'Inmunosupresor tópico (dermatología)': '#9C27B0',
  'AINE (inhibidor COX selectivo)': '#558B2F',
  'AINE (inhibidor COX-2 selectivo)': '#689F38',
  'AINE (inhibidor COX no selectivo)': '#7CB342',
  'AINE (inhibidor COX no selectivo potente)': '#8BC34A',
  'Corticoesteroide (glucocorticoide de acción intermedia)': '#FFB300',
  'Corticoesteroide (glucocorticoide de acción prolongada)': '#FFCA28',
  'Praziquantel': '#00838F',
  'Benzimidazol': '#0097A7',
  'Cholinérgico (antihelmíntico)': '#00ACC1',
  'Avemectina (macrocíclico lactona)': '#00B0FF',
  'Macrocíclico lactona': '#40C4FF',
  'Fenilpirazol': '#18FFFF',
  'Neonicotinoide': '#64FFDA',
  'Piretroide': '#69F0AE',
  'Formamidina': '#B2FF59',
  'Isoxazolina': '#EEFF41',
};
