services:
  database:
    image: postgres:16
    container_name: vetcloud-postgres
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "vetcloud"
      POSTGRES_PASSWORD: "vetcloud_secure_2024"
      POSTGRES_DB: "vetcloud"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vetcloud"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:6-alpine
    container_name: vetcloud-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  directus:
    image: directus/directus:11
    container_name: vetcloud-directus
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "vetcloud-super-secret-key-2024-change-me"
      ADMIN_EMAIL: "admin@vetcloud.local"
      ADMIN_PASSWORD: "Admin123!"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "vetcloud"
      DB_USER: "vetcloud"
      DB_PASSWORD: "vetcloud_secure_2024"

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      WEBSOCKETS_ENABLED: "true"

      STORAGE_LOCATIONS: "local"
      STORAGE_LOCAL_ROOT: "/directus/uploads"
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
