-- Migration: Add tutor columns to pets table
ALTER TABLE pets ADD COLUMN IF NOT EXISTS tutor_name VARCHAR(255);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS clinic_location VARCHAR(255);
