ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_password VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS clinic_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS veterinarian_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS clinic_phone VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS clinic_address TEXT;
