INSERT INTO diseases (name, scientific_name, species, category, severity, description, key_signs, diagnosis, treatment, prevention, prognosis, is_zoonotic, references_list) VALUES

-- DOG DISEASES
('Parvovirus Canino', 'Canine Parvovirus (CPV-2)', 'dog', 'infectious', 'severe',
'Enfermedad viral altamente contagiosa causada por el parvovirus canino tipo 2. Afecta principalmente el tracto gastrointestinal y el sistema inmune.',
'["Vómitos severos con sangre","Diarrea hemorrágica","Pérdida severa de apetito","Letargia y debilidad extrema","Fiebre alta (39.5-41°C)","Deshidratación rápida","Abdomen doloroso"]'::jsonb,
'{"clinicalExam":"Evaluación de signos clínicos, deshidratación, estado corporal. Historial de vacunación incompleta.","labTests":["Test rápido de antígeno fecal (ELISA)","Hemograma: leucopenia","Química sanguínea: hipoglucemia","Electrolitos: alteraciones"],"imaging":["Radiografía abdominal: distensión de asas intestinales"],"differentialDiagnosis":["Parasitismo severo","Gastroenteritis","Intoxicación alimentaria"]}'::jsonb,
'{"firstLine":["Hospitalización y fluidoterapia IV","Maropitant (Cerenia) 1-2 mg/kg SC q24h","Ampicilina 22 mg/kg IV q6h","Omeprazol 1 mg/kg IV q24h","Nutrición enteral suave"],"secondLine":["Favipiravir","Inmunoglobulinas antiparvovirus","Plasma fresco"],"emergency":"Shock séptico: resucitación con fluidos bolus, dobutamina si hipotensión.","duration":"5-7 días de hospitalización"}'::jsonb,
'["Vacunación completa según protocolo","Evitar contacto con heces contaminadas","No pasear cachorros hasta completar vacunación"]'::jsonb,
'guarded', false,
'["Greene CE, Sykes JE. Canine Parvovirus Infections. Infectious Diseases of the Dog and Cat. 4th ed.","AVMA - Canine Parvovirus Fact Sheet"]'::jsonb),

('Moquillo Canino', 'Canine Distemper Virus (CDV)', 'dog', 'infectious', 'severe',
'Enfermedad viral sistémica altamente contagiosa. Afecta tracto respiratorio, gastrointestinal, sistema nervioso y tejidos epiteliales.',
'["Fiebre bifásica","Secreción nasal y ocular mucopurulenta","Tos progresiva","Hiperqueratosis de almohadillas","Signos neurológicos: mioclonias, convulsiones"]'::jsonb,
'{"clinicalExam":"Signos sistémicos multifásicos, hiperqueratosis de almohadillas.","labTests":["PCR en hisopos","Inmunofluorescencia directa","Hemograma: leucopenia"],"imaging":["Radiografía torácica: patrón intersticial"],"differentialDiagnosis":["Influenza canina","Adenovirus"]}'::jsonb,
'{"firstLine":["Soporte intensivo: fluidoterapia IV","Antibióticos para secundarias","Nebulización"],"secondLine":["Interferón omega","Anticonvulsivantes si signos neurológicos"],"emergency":"Status epilépticus: Diazepam IV.","duration":"2-4 semanas"}'::jsonb,
'["Vacunación DHPPi","Refuerzo anual","Evitar contacto con wildlife"]'::jsonb,
'guarded', false,
'["Greene CE, Appel MJG. Canine Distemper. 4th ed."]'::jsonb),

('Leptospirosis Canina', 'Leptospira spp.', 'dog', 'infectious', 'severe',
'Enfermedad zoonótica causada por espiroquetas. Afecta hígado y riñones.',
'["Fiebre alta","Mialgias severas","Ictericia","Oliguria","Hemorragias petequiales"]'::jsonb,
'{"clinicalExam":"Ictericia, dolor renal, fiebre.","labTests":["MAT","PCR en sangre y orina","Química: elevación de ALT, creatinina"],"imaging":["Ecografía renal"],"differentialDiagnosis":["Hepatitis infecciosa","Piometra"]}'::jsonb,
'{"firstLine":["Fluidoterapia IV","Doxiciclina 10 mg/kg PO q12h por 2-4 semanas","Ampicilina IV"],"secondLine":["Penicilina G","Hemodiálisis"],"emergency":"Insuficiencia renal aguda: hemodiálisis.","duration":"2-4 semanas de antibióticos"}'::jsonb,
'["Vacunación anual","Evitar aguas estancadas","Control de roedores"]'::jsonb,
'guarded', true,
'["Sykes JE. Leptospirosis. 4th ed."]'::jsonb),

('Rabia', 'Rabies lyssavirus', 'dog', 'infectious', 'critical',
'Enfermedad viral zoonótica mortal. Sin tratamiento curativo.',
'["Cambios de comportamiento","Agresividad","Parálisis","Hidrofobia","Hipersecreción salival"]'::jsonb,
'{"clinicalExam":"Signos neurológicos progresivos. Diagnóstico definitivo post-mortem.","labTests":["IFA en tejido encefálico post-mortem"],"imaging":[],"differentialDiagnosis":["Encefalitis","Moquillo"]}'::jsonb,
'{"firstLine":["NO EXISTE TRATAMIENTO","Eutanasia humanitaria","Reporte obligatorio"],"secondLine":[],"emergency":"Protocolo de exposición para humanos.","duration":"Fatal en 100% de los casos"}'::jsonb,
'["Vacunación ANUAL obligatoria","Control de animales callejeros"]'::jsonb,
'grave', true,
'["WHO - Rabies Fact Sheet"]'::jsonb),

('Displasia Coxofemoral', 'Canine Hip Dysplasia', 'dog', 'musculoskeletal', 'moderate',
'Enfermedad degenerativa de la articulación coxofemoral. Más común en razas grandes.',
'["Cojera de extremidades posteriores","Dificultad para levantarse","Caminata de conejo","Atrofia muscular"]'::jsonb,
'{"clinicalExam":"Prueba de Ortolani positiva, dolor a la manipulación.","labTests":[],"imaging":["Radiografía ventrodorsal extendida","Clasificación OFA/FCI"],"differentialDiagnosis":["Osteocondritis","Ruptura de ligamento cruzado"]}'::jsonb,
'{"firstLine":["Control de peso","AINEs: Carprofen","Suplementos: Glucosamina","Fisioterapia"],"secondLine":["Infiltración intraarticular","Prótesis total de cadera"],"emergency":"Crisis de dolor: AINEs parenterales.","duration":"Manejo de por vida"}'::jsonb,
'["Selección genética","Control nutricional","Evitar ejercicio excesivo"]'::jsonb,
'good', false,
'["Smith GK. Hip Dysplasia. Small Animal Surgery. 5th ed."]'::jsonb),

('Dirofilariasis', 'Dirofilaria immitis', 'dog', 'parasitic', 'severe',
'Gusano del corazón transmitido por mosquitos.',
'["Tos crónica","Intolerancia al ejercicio","Disnea","Ascitis","Insuficiencia cardíaca"]'::jsonb,
'{"clinicalExam":"Soplo cardíaco, ingurgitación yugular.","labTests":["Test antígeno cardíaco","Microhematocrito"],"imaging":["Ecocardiografía","Radiografía torácica"],"differentialDiagnosis":["Enfermedad valvular","Neumonía"]}'::jsonb,
'{"firstLine":["Restricción de ejercicio","Melarsamina IM","Doxiciclina 4 semanas"],"secondLine":["Cirugía extractiva"],"emergency":"Tromboembolismo pulmonar: oxigenoterapia, anticoagulantes.","duration":"Tratamiento completo: 4 meses"}'::jsonb,
'["Profilaxis mensual: Moxidectina/Ivermectina","Control de mosquitos"]'::jsonb,
'good', false,
'["American Heartworm Society Guidelines"]'::jsonb),

('Diabetes Mellitus', 'Diabetes Mellitus Canine', 'dog', 'endocrine', 'moderate',
'Trastorno endocrino con hiperglucemia persistente.',
'["Polidipsia","Poliuria","Pérdida de peso","Cataratas","Letargia"]'::jsonb,
'{"clinicalExam":"Pérdida de peso, cataratas, hepatomegalia.","labTests":["Glucemia en ayuno >250 mg/dL","Glucosuria","Fructosamina >400 µmol/L"],"imaging":["Ecografía abdominal"],"differentialDiagnosis":["Cushing","Pancreatitis"]}'::jsonb,
'{"firstLine":["Insulina NPH/Caninsulin","Dieta alta en fibra","Ejercicio regular"],"secondLine":["Insulina glargina","Metformina"],"emergency":"Cetoacidosis: fluidoterapia IV, insulina regular.","duration":"Tratamiento de por vida"}'::jsonb,
'["Esterilización en hembras","Control de peso","Alimentación balanceada"]'::jsonb,
'good', false,
'["Nelson RW. Diabetes Mellitus. 8th ed."]'::jsonb),

('Pancreatitis', 'Pancreatitis Canina', 'dog', 'gastrointestinal', 'moderate',
'Inflamación del páncreas aguda o crónica.',
'["Vómitos recurrentes","Dolor abdominal","Anorexia","Diarrea"]'::jsonb,
'{"clinicalExam":"Dolor abdominal, deshidratación.","labTests":["Spec cPL","PLI sérica","Amilasa/lipasa"],"imaging":["Ecografía abdominal"],"differentialDiagnosis":["Hepatitis","Enfermedad inflamatoria intestinal"]}'::jsonb,
'{"firstLine":["NPO 24-48h","Fluidoterapia IV","Maropitant","Buprenorfina para dolor"],"secondLine":["Gabapentina","Pentoxifilina"],"emergency":"Pancreatitis hemorrágica: UCI, fluidoterapia agresiva.","duration":"Aguda: 3-5 días. Crónica: manejo dietético de por vida."}'::jsonb,
'["Dieta baja en grasa","Control de peso","Raciones fraccionadas"]'::jsonb,
'good', false,
'["Newman S. Pancreatitis in Dogs. 8th ed."]'::jsonb),

('Torsión Gástrica', 'Gastric Dilatation-Volvulus (GDV)', 'dog', 'gastrointestinal', 'critical',
'Emergencia quirúrgica donde el estómago se dilata y torsiona.',
'["Distensión abdominal","Esfuerzo por vomitar","Salivación excesiva","Taquicardia","Encías pálidas"]'::jsonb,
'{"clinicalExam":"Timpanismo abdominal, taquicardia.","labTests":["Hemograma","Química: acidosis, hiperpotasemia","Troponina I"],"imaging":["Radiografía: signo double bubble"],"differentialDiagnosis":["Dilatación gástrica simple","Obstrucción intestinal"]}'::jsonb,
'{"firstLine":["Descompreión urgente","Resucitación IV","CIRUGÍA URGENTE: gastropexia"],"secondLine":["Gastropexia profiláctica"],"emergency":"SHOCK: fluidoterapia masiva, dobutamina, plasma.","duration":"Hospitalización 3-5 días"}'::jsonb,
'["Alimentación fraccionada","Bol de alimentación lento","Gastropexia profiláctica"]'::jsonb,
'guarded', false,
'["Glickman LT. Canine GDV. JAVMA. 2000."]'::jsonb),

('Enfermedad Periodontal', 'Periodontal Disease Canine', 'dog', 'dental', 'moderate',
'Inflamación e infección de las estructuras del diente. Afecta al 80% de perros a los 3 años.',
'["Halitosis","Sarro","Encías rojas","Sangrado","Pérdida de dientes"]'::jsonb,
'{"clinicalExam":"Evaluación visual de sarro, gingivitis.","labTests":["Hemograma si infección"],"imaging":["Radiografías dentales intraorales"],"differentialDiagnosis":["Fractura dental","Tumor oral"]}'::jsonb,
'{"firstLine":["Limpieza dental bajo anestesia","Extracción de dientes comprometidos","Clorhexidina tópica"],"secondLine":["Cirugía periodontal"],"emergency":"Absceso dental: drenaje + antibióticos.","duration":"Mantenimiento dental diario"}'::jsonb,
'["Cepillado diario","Dietas dentales","Limpieza profesional anual"]'::jsonb,
'good', false,
'["AVDC - Veterinary Dental Nomenclature"]'::jsonb),

('Dermatitis Atópica', 'Canine Atopic Dermatitis', 'dog', 'dermatological', 'moderate',
'Enfermedad inflamatoria de la piel mediada por IgE.',
'["Prurito intenso","Rascado","Otitis recurrente","Dermatitis podal","Infecciones secundarias"]'::jsonb,
'{"clinicalExam":"Distribución: axilas, ingles, podal.","labTests":["Raspado de piel","Citología cutánea","Alergenos IgE"],"imaging":[],"differentialDiagnosis":["DAPP","Dermatofitosis","Sarna"]}'::jsonb,
'{"firstLine":["Oclacitinib (Apoquel)","Corticoides tapering","Antihistamínicos"],"secondLine":["Ciclosporina","Inmunoterapia","Cytopoint"],"emergency":"Auto-traumatismo: collar isabelino + corticoides.","duration":"Manejo de por vida"}'::jsonb,
'["Control de alérgenos","Suplementación omega-3","Baños regulares"]'::jsonb,
'guarded', false,
'["Olivry T. Treatment of Canine Atopic Dermatitis. 2015."]'::jsonb),

('Cataratas', 'Cataracts Canine', 'dog', 'ocular', 'moderate',
'Opacificación del cristalino que impide el paso de la luz.',
'["Opacidad blanca en pupila","Ceguera parcial","Nistagmo"]'::jsonb,
'{"clinicalExam":"Examen oftalmoscópico.","labTests":["Ecografía ocular","Tonometría","ERG"],"imaging":["Ecografía B-scan"],"differentialDiagnosis":["Esclerosis nuclear","Glaucoma"]}'::jsonb,
'{"firstLine":["Facoemulsificación + lente intraocular","Gotas post-operatorias"],"secondLine":["Extracción extracapsular"],"emergency":"Glaucoma: manitol IV + timolol tópico.","duration":"Recuperación: 2-6 semanas"}'::jsonb,
'["Cribado genético","Control de diabetes"]'::jsonb,
'good', false,
'["Gelatt KN. Veterinary Ophthalmology. 5th ed."]'::jsonb),

('Enfermedad Renal Crónica', 'Chronic Kidney Disease', 'dog', 'renal', 'moderate',
'Pérdida progresiva e irreversible de la función renal.',
'["Polidipsia","Poliuria","Pérdida de peso","Vómitos","Halitosis urémica"]'::jsonb,
'{"clinicalExam":"Pérdida de peso, halitosis.","labTests":["Creatinina y BUN elevadas","SDMA >18 µg/dL","Análisis de orina"],"imaging":["Ecografía renal"],"differentialDiagnosis":["Nefropatía por amiloidosis","Pielonefritis"]}'::jsonb,
'{"firstLine":["Dieta renal","Fluidoterapia SC en casa","EPO si anemia"],"secondLine":["Telmisartán","Calcitriol"],"emergency":"Crisis urémica: fluidoterapia IV, diálisis.","duration":"Manejo de por vida"}'::jsonb,
'["Dieta de calidad","Hidratación adecuada","Evitar nefrotóxicos"]'::jsonb,
'guarded', false,
'["IRIS - Staging CKD"]'::jsonb),

('Linfoma Canino', 'Canine Lymphoma', 'dog', 'oncological', 'severe',
'Neoplasia de células linfoides, una de las más comunes.',
'["Linfadenopatía","Pérdida de peso","Anorexia","Fiebre"]'::jsonb,
'{"clinicalExam":"Nodos linfáticos agrandados.","labTests":["FNA","Biopsia con inmunohistoquímica","Hemograma"],"imaging":["Radiografía torácica","Ecografía abdominal"],"differentialDiagnosis":["Hiperplasia reactiva","Ehrlichia"]}'::jsonb,
'{"firstLine":["Quimioterapia CHOP","Prednisona"],"secondLine":["Lomustina","Toceranib"],"emergency":"Hipercalcemia: fluidoterapia + furosemida.","duration":"Quimioterapia: 25-30 semanas"}'::jsonb,
'["No hay prevención conocida","Castración puede reducir riesgo"]'::jsonb,
'guarded', false,
'["Vail DM. Lymphoma. Small Animal Clinical Oncology. 5th ed."]'::jsonb),

('Otitis Externa', 'Otitis Externa Canine', 'dog', 'dermatological', 'mild',
'Inflamación del canal auditivo externo.',
'["Sacudida de cabeza","Rascado de orejas","Secreción","Mal olor"]'::jsonb,
'{"clinicalExam":"Otoscopia: evaluación del canal.","labTests":["Citología del cerumen","Cultivo si resistente"],"imaging":["Radiografías del oído si sospecha media"],"differentialDiagnosis":["Otitis media","Otodecosis"]}'::jsonb,
'{"firstLine":["Limpieza del canal","Gotas otológicas","Tratar causa subyacente"],"secondLine":["Antibióticos sistémicos","Cirugía si crónica"],"emergency":"Otitis interna: internamiento.","duration":"Aguda: 7-14 días"}'::jsonb,
'["Limpieza preventiva semanal","Secar orejas después de nadar"]'::jsonb,
'excellent', false,
'["Cole LK. Otitis Externa. Vet Clin North Am. 2004."]'::jsonb),

-- CAT DISEASES
('Leucemia Felina', 'Feline Leukemia Virus (FeLV)', 'cat', 'infectious', 'severe',
'Infección retroviral que causa inmunosupresión y neoplasias.',
'["Pérdida de peso","Letargia","Anemia","Infecciones frecuentes"]'::jsonb,
'{"clinicalExam":"Anemia, linfadenopatía.","labTests":["ELISA p27","IFA","Hemograma"],"imaging":["Radiografía torácica"],"differentialDiagnosis":["FIV","Toxoplasmosis"]}'::jsonb,
'{"firstLine":["Aislamiento","Soporte nutricional","Interferón","AZT"],"secondLine":["Quimioterapia si linfoma"],"emergency":"Shock séptico: antibióticos IV.","duration":"Enfermedad de por vida"}'::jsonb,
'["Vacunación FeLV","Test antes de vacunar","Mantener gatos en interiores"]'::jsonb,
'poor', false,
'["Hartmann K. Feline Leukemia Virus. 4th ed."]'::jsonb),

('Virus de Inmunodeficiencia Felina', 'Feline Immunodeficiency Virus (FIV)', 'cat', 'infectious', 'moderate',
'Infección retroviral que causa inmunodeficiencia progresiva.',
'["Infecciones recurrentes","Estomatitis","Pérdida de peso","Linfadenopatía"]'::jsonb,
'{"clinicalExam":"Estomatitis, infecciones recurrentes.","labTests":["ELISA FIV","Western Blot","PCR"],"imaging":[],"differentialDiagnosis":["FeLV","Enfermedad dental"]}'::jsonb,
'{"firstLine":["Manejo de infecciones","AZT","Interferón"],"secondLine":["Inmunomoduladores","Extracción dental"],"emergency":"Infección oportunista: antibióticos IV.","duration":"Manejo de por vida"}'::jsonb,
'["No hay vacuna","Mantener en interiores","Castrar machos"]'::jsonb,
'guarded', false,
'["Levy J. FIV Infection. 4th ed."]'::jsonb),

('Peritonitis Infecciosa Felina', 'Feline Infectious Peritonitis (FIP)', 'cat', 'infectious', 'critical',
'Enfermedad inmunomediada causada por mutación del coronavirus felino.',
'["Líquido abdominal amarillo","Fiebre persistente","Pérdida de peso","Signos neurológicos"]'::jsonb,
'{"clinicalExam":"Líquido ascítico, fiebre, hepatomegalia.","labTests":["Análisis de líquido: Rivalta positiva","PCR","Hemograma"],"imaging":["Ecografía abdominal"],"differentialDiagnosis":["Carcinomatosis","Insuficiencia cardíaca"]}'::jsonb,
'{"firstLine":["GS-441524 (antiviral oral) por 84 días","Supportivo"],"secondLine":["GC376","Prednisona"],"emergency":"Dificultad respiratoria: toracocentesis.","duration":"Tratamiento GS-441524: 84 días"}'::jsonb,
'["Higiene estricta","Reducción de estrés","Evitar colonias superpobladas"]'::jsonb,
'poor', false,
'["Pedersen NC. GS-441524 for FIP. J Feline Med Surg. 2019."]'::jsonb),

('Calicivirus Felino', 'Feline Calicivirus (FCV)', 'cat', 'infectious', 'moderate',
'Infección viral respiratoria con úlceras orales.',
'["Úlceras en lengua y paladar","Secreción nasal","Conjuntivitis","Fiebre"]'::jsonb,
'{"clinicalExam":"Úlceras linguales, secreción nasal.","labTests":["PCR en hisopo orofaringeo"],"imaging":[],"differentialDiagnosis":["Herpesvirus","Estomatitis"]}'::jsonb,
'{"firstLine":["Fluidoterapia si deshidratación","Antibióticos para secundarias","Analgesia: Buprenorfina"],"secondLine":["Famciclovir"],"emergency":"Pneumonia: oxigenoterapia.","duration":"7-14 días"}'::jsonb,
'["Vacunación intranasal u oral","Aislamiento de enfermos"]'::jsonb,
'good', false,
'["Radford AD. Feline Calicivirus. 4th ed."]'::jsonb),

('Cardiomiopatía Hipertrófica', 'Hypertrophic Cardiomyopathy (HCM)', 'cat', 'cardiovascular', 'severe',
'Enfermedad cardíaca más común en gatos. Engrosamiento del miocardio.',
'["Disnea","Taquicardia","Soplo cardíaco","Tromboembolismo"]'::jsonb,
'{"clinicalExam":"Soplo sistólico, galope.","labTests":["NT-proBNP","Troponina I","ECG"],"imaging":["Ecocardiografía DOPPLER","Radiografía torácica"],"differentialDiagnosis":["Hipertiroidismo","Hipertensión"]}'::jsonb,
'{"firstLine":["Furosemida","Atenolol","Clopidogrel","Oxigenoterapia"],"secondLine":["Enalapril","Pimobendan"],"emergency":"Tromboembolismo: heparina + analgesia.","duration":"Tratamiento de por vida"}'::jsonb,
'["Screening genético","Ecocardiografía preventiva"]'::jsonb,
'guarded', false,
'["ACVIM - Feline Cardiomyopathy Guidelines"]'::jsonb),

('Enfermedad Renal Crónica Felina', 'Chronic Kidney Disease (CKD) Feline', 'cat', 'renal', 'moderate',
'La causa más común de muerte en gatos geriátricos.',
'["Polidipsia","Pérdida de peso","Pelo deteriorado","Vómitos","Halitosis urémica"]'::jsonb,
'{"clinicalExam":"Pérdida de peso, deshidratación.","labTests":["Creatinina elevada","SDMA >18","UPC >0.4"],"imaging":["Ecografía renal"],"differentialDiagnosis":["Pielonefritis","Amiloidosis"]}'::jsonb,
'{"firstLine":["Dieta renal","Fluidoterapia SC","EPO si anemia"],"secondLine":["Telmisartán","Calcitriol"],"emergency":"Crisis urémica: fluidoterapia IV.","duration":"Manejo de por vida"}'::jsonb,
'["Hidratación adecuada","Dieta de calidad","Screening anual >7 años"]'::jsonb,
'guarded', false,
'["IRIS - CKD in Cats"]'::jsonb),

('Hipertiroidismo', 'Hyperthyroidism Feline', 'cat', 'endocrine', 'moderate',
'Producción excesiva de hormonas tiroideas.',
'["Pérdida de peso con apetito voraz","Hiperactividad","Taquicardia","Masa cervical"]'::jsonb,
'{"clinicalExam":"Masa cervical, taquicardia.","labTests":["T4 total elevada","Hemograma","Química"],"imaging":["Ecografía tiroidea"],"differentialDiagnosis":["Diabetes","Insuficiencia renal"]}'::jsonb,
'{"firstLine":["Metimazol 2.5-5 mg PO q12-24h","Methimazol tópico"],"secondLine":["Yodo radioactivo I-131","Cirugía tiroidectomía","Dieta y/d"],"emergency":"Crisis tirotóxica: β-bloqueantes.","duration":"Metimazol: 1-4 semanas para efecto"}'::jsonb,
'["Screening T4 anual >7 años"]'::jsonb,
'excellent', false,
'["Peterson ME. Hyperthyroidism in Cats. 8th ed."]'::jsonb),

('Síndrome Urológico Felino', 'Feline Lower Urinary Tract Disease (FLUTD)', 'cat', 'renal', 'severe',
'Trastornos del tracto urinario inferior.',
'["Esfuerzo para orinar","Hematuria","Orinar fuera del arenero","Anuria"]'::jsonb,
'{"clinicalExam":"Vejiga dura, dolor abdominal.","labTests":["Análisis de orina","Urocultivo","Química"],"imaging":["Radiografía abdominal","Ecografía vesical"],"differentialDiagnosis":["Cistitis bacteriana","Neoplasia vesical"]}'::jsonb,
'{"firstLine":["Desobstrucción uretral","Fluidoterapia IV","Dieta urinaria"],"secondLine":["Perineostomía","Ansiolíticos"],"emergency":"OBSTRUCCIÓN URETRAL: EMERGENCIA.","duration":"Dietoterapia de por vida"}'::jsonb,
'["Dieta urinaria húmeda","Fuentes de agua","Areneros limpios","Reducción de estrés"]'::jsonb,
'guarded', false,
'["WSAVA - FLUTD Guidelines"]'::jsonb),

('Dermatofitosis', 'Dermatophytosis (Microsporum canis)', 'cat', 'dermatological', 'mild',
'Infección fúngica de la piel y pelo. Zoonótica.',
'["Lesiones circulares alopecicas","Costras","Pérdida de pelo en parches"]'::jsonb,
'{"clinicalExam":"Lesiones redondeadas.","labTests":["Lámpara Wood","KOH","Cultivo en DTM"],"imaging":[],"differentialDiagnosis":["Dermatitis alérgica","Sarna"]}'::jsonb,
'{"firstLine":["Itraconazol 5 mg/kg","Shampoo clorhexidina","Desinfección del ambiente"],"secondLine":["Terbinafina","Micafungina"],"emergency":"","duration":"6-8 semanas hasta 2 cultivos negativos"}'::jsonb,
'["Aislamiento","Desinfección","Exámenes regulares"]'::jsonb,
'excellent', true,
'["Moriello KA. Dermatophytosis in Cats. 4th ed."]'::jsonb),

('Obesidad Felina', 'Feline Obesity', 'cat', 'nutritional', 'moderate',
'Más del 60% de gatos domésticos están con sobrepeso.',
'["IMC >30%","Pérdida de definición de cintura","Intolerancia al ejercicio"]'::jsonb,
'{"clinicalExam":"Evaluación BCS 1-9.","labTests":["Hemograma","Glucosa y fructosamina"],"imaging":[],"differentialDiagnosis":["Hipertiroidismo","Diabetes"]}'::jsonb,
'{"firstLine":["Dieta -20% calorías","Alimentación fraccionada","Ejercicio enriquecido"],"secondLine":["Dieta metabolic","Péptidos de saciedad"],"emergency":"Lipidosis hepática si anorexia >48h.","duration":"Programa: 3-6 meses"}'::jsonb,
'["Control de porciones","Ejercicio diario","Medir peso mensual"]'::jsonb,
'good', false,
'["German AJ. Obesity in Dogs and Cats. J Nutr. 2006."]'::jsonb),

('Asma Felino', 'Feline Asthma', 'cat', 'respiratory', 'moderate',
'Enfermedad alérgica de las vías aéreas inferiores.',
'["Tos seca paroxística","Disnea expiratoria","Respiración abdominal"]'::jsonb,
'{"clinicalExam":"Sibilancias, crepitantes.","labTests":["Hemograma: eosinofilia","Citología BAL: eosinófilos >50%"],"imaging":["Radiografía torácica: patrón broncointersticial"],"differentialDiagnosis":["Parasitismo pulmonar","Insuficiencia cardíaca"]}'::jsonb,
'{"firstLine":["Prednisolona","Terbutalina","Evitar alérgenos"],"secondLine":["Ciclosporina"],"emergency":"Broncoespasmo severo: oxigenoterapia + corticoides IV.","duration":"Manejo de por vida"}'::jsonb,
'["Evitar alérgenos","Ambiente limpio"]'::jsonb,
'good', false,
'["Levy LR. Feline Asthma. 8th ed."]'::jsonb),

('Reabsorción Dental Felina', 'Feline Odontoclastic Resorptive Lesions (FORL)', 'cat', 'dental', 'moderate',
'Destrucción progresiva del diente por odontoclastos.',
'["Dolor oral","Babeo","Rechazo de alimento seco","Fractura dental"]'::jsonb,
'{"clinicalExam":"Lesiones rosadas en encía.","labTests":[],"imaging":["Radiografías dentales intraorales"],"differentialDiagnosis":["Enfermedad periodontal","Neoplasia oral"]}'::jsonb,
'{"firstLine":["Extracción dental completa","Analgesia post-operatoria"],"secondLine":["Corona dental (Tipo II)"],"emergency":"Dolor severo: analgesia multimodal.","duration":"Recuperación: 7-10 días"}'::jsonb,
'["Exámenes dentales anuales","Radiografías regulares"]'::jsonb,
'good', false,
'["Gorrel C. Tooth Resorption. Elsevier; 2013."]'::jsonb),

('Toxoplasmosis', 'Toxoplasma gondii', 'cat', 'parasitic', 'moderate',
'Parasitosis donde el gato es hospedador definitivo.',
'["Fiebre","Pérdida de peso","Signos neurológicos","Uveítis"]'::jsonb,
'{"clinicalExam":"Fiebre, mialgias, neurológicos.","labTests":["Serología IgG/IgM","PCR","Oocistos en heces"],"imaging":["MRI craneal si neurológicos"],"differentialDiagnosis":["FIP","FeLV/FIV"]}'::jsonb,
'{"firstLine":["Clindamicina 12.5-25 mg/kg PO q12h por 2-4 semanas","Ponamicina"],"secondLine":["Prednisona si uveítis"],"emergency":"Encefalitis: antibióticos IV.","duration":"2-4 semanas"}'::jsonb,
'["Cocinar carne","Limpiar arenero diariamente","Lavarse las manos"]'::jsonb,
'good', true,
'["Dubey JP. Toxoplasmosis in Cats. 4th ed."]'::jsonb),

('Rinotraqueítis Felina', 'Feline Herpesvirus-1 (FHV-1)', 'cat', 'infectious', 'moderate',
'Infección viral respiratoria causada por herpesvirus.',
'["Estornudos","Secreción nasal profusa","Conjuntivitis severa","Queratitis dendrítica"]'::jsonb,
'{"clinicalExam":"Conjuntivitis, queratitis, úlceras nasales.","labTests":["PCR en hisopo","Citología: células multinucleadas"],"imaging":[],"differentialDiagnosis":["Calicivirus","Chlamydia"]}'::jsonb,
'{"firstLine":["Famciclovir 90 mg/kg PO q8-12h","Gotas oculares: Cidofovir","Nebulización"],"secondLine":["L-lisina","Interferón"],"emergency":"Úlceras corneales profundas: oftalmólogo urgente.","duration":"Signos agudos: 7-14 días"}'::jsonb,
'["Vacunación","Higiene en guarderías","Reducción de estrés"]'::jsonb,
'good', false,
'["Thiry E. Feline Herpesvirus. 4th ed."]'::jsonb);
